'\" p
.\" -*- nroff -*-
.TH "ovn-controller-vtep" 8 "ovn-controller-vtep" "Open vSwitch 2\[char46]4\[char46]90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH "NAME"
.PP
ovn-controller-vtep \- Open Virtual Network local controller for
vtep enabled physical switches\[char46]
.SH "SYNOPSIS"
.PP
\fBovn\-controller\-vtep\fR [\fIoptions\fR]
[\fI\-\-vtep-db=vtep-database\fR] [\fI\-\-ovnsb-db=ovnsb-database\fR]
.SH "DESCRIPTION"
.PP
\fBovn\-controller\-vtep\fR is the local controller daemon in
OVN, the Open Virtual Network, for VTEP enabled physical switches\[char46]
It connects up to the OVN Southbound database (see
\fBovn\-sb\fR(5)) over the OVSDB protocol, and down to the VTEP
database (see \fBvtep\fR(5)) over the OVSDB protocol\[char46]
.SH "CONFIGURATION"
.PP
\fBovn\-controller\-vtep\fR retrieves its configuration
information from both the ovnsb and the vtep database\[char46]  If the
database locations are not given from command line, the default
is the \fBdb\[char46]sock\fR in local OVSDB\(cqs \(cqrun\(cq directory\[char46]
The datapath location must take one of the following forms:
.RS
.IP \(bu
\fBssl:\fIip\fB:\fIport\fB\fR
.IP
The specified SSL \fIport\fR on the host at the given
\fIip\fR, which must be expressed as an IP address (not a DNS
name) in IPv4 or IPv6 address format\[char46]  If \fIip\fR is an IPv6
address, then wrap \fIip\fR with square brackets, e\[char46]g\[char46]:
\fBssl:[::1]:6640\fR\[char46]  The \fB\-\-private\-key\fR,
\fB\-\-certificate\fR and either of \fB\-\-ca\-cert\fR
or \fB\-\-bootstrap\-ca\-cert\fR options are mandatory when this
form is used\[char46]
.IP \(bu
\fBtcp:\fIip\fB:\fIport\fB\fR
.IP
Connect to the given TCP \fIport\fR on \fIip\fR, where
\fIip\fR can be IPv4 or IPv6 address\[char46] If \fIip\fR is an
IPv6 address, then wrap \fIip\fR with square brackets, e\[char46]g\[char46]:
\fBtcp:[::1]:6640\fR\[char46]
.IP \(bu
\fBunix:\fIfile\fB\fR
.IP
On POSIX, connect to the Unix domain server socket named
\fIfile\fR\[char46]
.IP
On Windows, connect to a localhost TCP port whose value is written
in \fIfile\fR\[char46]
.RE
