'\" p
.\" -*- nroff -*-
.TH "ovn-ctl" 8 "ovn-ctl" "Open vSwitch 2\[char46]7\[char46]90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.PP
.SH "NAME"
.PP
.PP
ovn-ctl \- Open Virtual Network northbound daemon lifecycle utility
.SH "SYNOPSIS"
.PP
\fBovn\-ctl\fR [\fIoptions\fR] \fIcommand\fR
.SH "DESCRIPTION"
.PP
.PP
This program is intended to be invoked internally by Open Virtual Network startup scripts\[char46] System administrators should not normally invoke it directly\[char46]
.SH "COMMANDS"
.TP
\fBstart_northd\fR
.TQ .5in
\fBstart_controller\fR
.TQ .5in
\fBstart_controller_vtep\fR
.TQ .5in
\fBstop_northd\fR
.TQ .5in
\fBstop_controller\fR
.TQ .5in
\fBstop_controller_vtep\fR
.TQ .5in
\fBrestart_northd\fR
.TQ .5in
\fBrestart_controller\fR
.TQ .5in
\fBrestart_controller_vtep\fR
.TQ .5in
\fBpromote_ovnnb\fR
.TQ .5in
\fBpromote_ovnsb\fR
.TQ .5in
\fBdemote_ovnnb\fR
.TQ .5in
\fBdemote_ovnsb\fR
.TQ .5in
\fBstatus_ovnnb\fR
.TQ .5in
\fBstatus_ovnsb\fR
.SH "OPTIONS"
.PP
\fB\-\-ovn\-northd\-priority=\fINICE\fB\fR
.PP
\fB\-\-ovn\-northd\-wrapper=\fIWRAPPER\fB\fR
.PP
\fB\-\-ovn\-controller\-priority=\fINICE\fB\fR
.PP
\fB\-\-ovn\-controller\-wrapper=\fIWRAPPER\fB\fR
.PP
\fB\-h\fR | \fB\-\-help\fR
.SH "FILE LOCATION OPTIONS"
.PP
\fB\-\-db\-sock=\fISOCKET\fB\fR
.PP
\fB\-\-db\-nb\-file=\fIFILE\fB\fR
.PP
\fB\-\-db\-sb\-file=\fIFILE\fB\fR
.PP
\fB\-\-db\-nb\-schema=\fIFILE\fB\fR
.PP
\fB\-\-db\-sb\-schema=\fIFILE\fB\fR
.PP
\fB\-\-db\-sb\-create\-insecure\-remote=\fIyes|no\fB\fR
.PP
\fB\-\-db\-nb\-create\-insecure\-remote=\fIyes|no\fB\fR
.PP
\fB\-\-ovn\-controller\-ssl\-key=\fIKEY\fB\fR
.PP
\fB\-\-ovn\-controller\-ssl\-cert=\fICERT\fB\fR
.PP
\fB\-\-ovn\-controller\-ssl\-ca\-cert=\fICERT\fB\fR
.PP
\fB\-\-ovn\-controller\-ssl\-bootstrap\-ca\-cert=\fICERT\fB\fR
.SH "ADDRESS AND PORT OPTIONS"
.PP
\fB\-\-db\-nb\-sync\-from\-addr=\fIIP ADDRESS\fB\fR
.PP
\fB\-\-db\-nb\-sync\-from\-port=\fIPORT NUMBER\fB\fR
.PP
\fB\-\-db\-nb\-sync\-from\-proto=\fIPROTO\fB\fR
.PP
\fB\-\-db\-sb\-sync\-from\-addr=\fIIP ADDRESS\fB\fR
.PP
\fB\-\-db\-sb\-sync\-from\-port=\fIPORT NUMBER\fB\fR
.PP
\fB\-\-db\-sb\-sync\-from\-proto=\fIPROTO\fB\fR
.SH "CONFIGURATION FILES"
.PP
.PP
Following are the optional configuration files\[char46] If present, it should be located in the etc dir
.SS "ovnnb-active\[char46]conf"
.PP
.PP
If present, this file should hold the url to connect to the active Northbound DB server
.PP
\fBtcp:x\[char46]x\[char46]x\[char46]x:6641\fR
.SS "ovnsb-active\[char46]conf"
.PP
.PP
If present, this file should hold the url to connect to the active Southbound DB server
.PP
\fBtcp:x\[char46]x\[char46]x\[char46]x:6642\fR
.SS "ovn-northd-db-params\[char46]conf"
.PP
.PP
If present, start_northd will not start the DB server even if \fB\-\-ovn\-manage\-ovsdb=yes\fR\[char46] This file should hold the database url parameters to be passed to ovn-northd\[char46]
.PP
\fB\-\-ovnnb\-db=tcp:x\[char46]x\[char46]x\[char46]x:6641 \-\-ovnsb\-db=tcp:x\[char46]x\[char46]x\[char46]x:6642\fR
.SH "EXAMPLE USAGE"
.SS "Run ovn-controller on a host already running OVS"
.PP
\fB# ovn\-ctl start_controller\fR
.SS "Run ovn-northd on a host already running OVS"
.PP
\fB# ovn\-ctl start_northd\fR
.SS "All-in-one OVS+OVN for testing"
.PP
\fB# ovs\-ctl start \-\-system\-id=\(dqrandom\(dq\fR
.PP
\fB# ovn\-ctl start_northd\fR
.PP
\fB# ovn\-ctl start_controller\fR
.SS "Promote and demote ovsdb servers"
.PP
\fB# ovn\-ctl promote_ovnnb\fR
.PP
\fB# ovn\-ctl promote_ovnsb\fR
.PP
\fB# ovn\-ctl \-\-db\-nb\-sync\-from\-addr=x\[char46]x\[char46]x\[char46]x \-\-db\-nb\-sync\-from\-port=6641 demote_ovnnb\fR
.PP
\fB# ovn\-ctl \-\-db\-sb\-sync\-from\-addr=x\[char46]x\[char46]x\[char46]x \-\-db\-sb\-sync\-from\-port=6642 demote_ovnsb\fR
