'\" p
.\" -*- nroff -*-
.TH "ovn-ctl" 8 "ovn-ctl" "Open vSwitch 2\[char46]4\[char46]90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH "NAME"
.PP
ovn-ctl \- Open Virtual Network northbound daemon lifecycle utility
.SH "SYNOPSYS"
.PP
\fBovn\-ctl\fR [\fIoptions\fR] \fIcommand\fR
.SH "DESCRIPTION"
.PP
This program is intended to be invoked internally by Open Virtual Network
startup scripts\[char46]  System administrators should not normally invoke it directly\[char46]
.SH "COMMANDS"
.RS
.TP
\fBstart_northd\fR
.TQ .5in
\fBstart_controller\fR
.TQ .5in
\fBstop_northd\fR
.TQ .5in
\fBstop_controller\fR
.TQ .5in
\fBrestart_northd\fR
.TQ .5in
\fBrestart_controller\fR
.RE
.SH "OPTIONS"
.PP
\fB\-\-ovn\-northd\-priority=\fINICE\fB\fR
.PP
\fB\-\-ovn\-northd\-wrapper=\fIWRAPPER\fB\fR
.PP
\fB\-\-ovn\-controller\-priority=\fINICE\fB\fR
.PP
\fB\-\-ovn\-controller\-wrapper=\fIWRAPPER\fB\fR
.PP
\fB\-h\fR | \fB\-\-help\fR
.SH "FILE LOCATION OPTIONS"
.PP
\fB\-\-db\-sock==\fISOCKET\fB\fR
.PP
\fB\-\-db\-nb\-file==\fIFILE\fB\fR
.PP
\fB\-\-db\-sb\-file==\fIFILE\fB\fR
.PP
\fB\-\-db\-nb\-schema==\fIFILE\fB\fR
.PP
\fB\-\-db\-sb\-schema==\fIFILE\fB\fR
.SH "EXAMPLE USAGE"
.SS "Run ovn-controller on a host already running OVS"
.PP
\fB# ovn\-ctl start_controller\fR
.SS "Run ovn-northd on a host already running OVS"
.PP
\fB# ovn\-ctl start_northd\fR
.SS "All-in-one OVS+OVN for testing"
.PP
\fB# ovs\-ctl start \-\-system\-id=\(dqrandom\(dq\fR
.PP
\fB# ovn\-ctl start_northd\fR
.PP
\fB# ovn\-ctl start_controller\fR
