'\" p
.\" -*- nroff -*-
.TH "ovn-controller" 8 "ovn-controller" "Open vSwitch 2\[char46]10\[char46]90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.PP
.SH "NAME"
.PP
.PP
ovn-controller \- Open Virtual Network local controller
.SH "SYNOPSIS"
.PP
\fBovn\-controller\fR [\fIoptions\fR] [\fIovs-database\fR]
.SH "DESCRIPTION"
.PP
.PP
\fBovn\-controller\fR is the local controller daemon for OVN, the Open Virtual Network\[char46] It connects up to the OVN Southbound database (see \fBovn\-sb\fR(5)) over the OVSDB protocol, and down to the Open vSwitch database (see \fBovs\-vswitchd\[char46]conf\[char46]db\fR(5)) over the OVSDB protocol and to \fBovs\-vswitchd\fR(8) via OpenFlow\[char46] Each hypervisor and software gateway in an OVN deployment runs its own independent copy of \fBovn\-controller\fR; thus, \fBovn\-controller\fR\(cqs downward connections are machine-local and do not run over a physical network\[char46]
.SH "ACL LOGGING"
.PP
.PP
ACL log messages are logged through \fBovn\-controller\fR\(cqs logging mechanism\[char46] ACL log entries have the module \fBacl_log\fR at log level \fBinfo\fR\[char46] Configuring logging is described below in the \fBLogging Options\fR section\[char46]
.SH "OPTIONS"
.SS "Daemon Options"
.TP
\fB\-\-pidfile\fR[\fB=\fR\fIpidfile\fR]
Causes a file (by default, \fB\fIprogram\fB\[char46]pid\fR) to be created indicating the PID of the running process\[char46] If the \fIpidfile\fR argument is not specified, or if it does not begin with \fB/\fR, then it is created in \fB/var/run/openvswitch\fR\[char46]
.IP
If \fB\-\-pidfile\fR is not specified, no pidfile is created\[char46]
.TP
\fB\-\-overwrite\-pidfile\fR
By default, when \fB\-\-pidfile\fR is specified and the specified pidfile already exists and is locked by a running process, the daemon refuses to start\[char46] Specify \fB\-\-overwrite\-pidfile\fR to cause it to instead overwrite the pidfile\[char46]
.IP
When \fB\-\-pidfile\fR is not specified, this option has no effect\[char46]
.TP
\fB\-\-detach\fR
Runs this program as a background process\[char46] The process forks, and in the child it starts a new session, closes the standard file descriptors (which has the side effect of disabling logging to the console), and changes its current directory to the root (unless \fB\-\-no\-chdir\fR is specified)\[char46] After the child completes its initialization, the parent exits\[char46]
.TP
\fB\-\-monitor\fR
Creates an additional process to monitor this program\[char46] If it dies due to a signal that indicates a programming error (\fBSIGABRT\fR, \fBSIGALRM\fR, \fBSIGBUS\fR, \fBSIGFPE\fR, \fBSIGILL\fR, \fBSIGPIPE\fR, \fBSIGSEGV\fR, \fBSIGXCPU\fR, or \fBSIGXFSZ\fR) then the monitor process starts a new copy of it\[char46] If the daemon dies or exits for another reason, the monitor process exits\[char46]
.IP
This option is normally used with \fB\-\-detach\fR, but it also functions without it\[char46]
.TP
\fB\-\-no\-chdir\fR
By default, when \fB\-\-detach\fR is specified, the daemon changes its current working directory to the root directory after it detaches\[char46] Otherwise, invoking the daemon from a carelessly chosen directory would prevent the administrator from unmounting the file system that holds that directory\[char46]
.IP
Specifying \fB\-\-no\-chdir\fR suppresses this behavior, preventing the daemon from changing its current working directory\[char46] This may be useful for collecting core files, since it is common behavior to write core dumps into the current working directory and the root directory is not a good directory to use\[char46]
.IP
This option has no effect when \fB\-\-detach\fR is not specified\[char46]
.TP
\fB\-\-no\-self\-confinement\fR
By default this daemon will try to self-confine itself to work with files under well-known directories whitelisted at build time\[char46] It is better to stick with this default behavior and not to use this flag unless some other Access Control is used to confine daemon\[char46] Note that in contrast to other access control implementations that are typically enforced from kernel-space (e\[char46]g\[char46] DAC or MAC), self-confinement is imposed from the user-space daemon itself and hence should not be considered as a full confinement strategy, but instead should be viewed as an additional layer of security\[char46]
.TP
\fB\-\-user=\fR\fIuser\fR\fB:\fR\fIgroup\fR
Causes this program to run as a different user specified in \fIuser\fR\fB:\fR\fIgroup\fR, thus dropping most of the root privileges\[char46] Short forms \fIuser\fR and \fB:\fR\fIgroup\fR are also allowed, with current user or group assumed, respectively\[char46] Only daemons started by the root user accepts this argument\[char46]
.IP
On Linux, daemons will be granted \fBCAP_IPC_LOCK\fR and \fBCAP_NET_BIND_SERVICES\fR before dropping root privileges\[char46] Daemons that interact with a datapath, such as \fBovs\-vswitchd\fR, will be granted three additional capabilities, namely \fBCAP_NET_ADMIN\fR, \fBCAP_NET_BROADCAST\fR and \fBCAP_NET_RAW\fR\[char46] The capability change will apply even if the new user is root\[char46]
.IP
On Windows, this option is not currently supported\[char46] For security reasons, specifying this option will cause the daemon process not to start\[char46]
.SS "Logging Options"
.TP
\fB\-v\fR[\fIspec\fR]
.TQ .5in
\fB\-\-verbose=\fR[\fIspec\fR]
Sets logging levels\[char46] Without any \fIspec\fR, sets the log level for every module and destination to \fBdbg\fR\[char46] Otherwise, \fIspec\fR is a list of words separated by spaces or commas or colons, up to one from each category below:
.RS
.IP \(bu
A valid module name, as displayed by the \fBvlog/list\fR command on \fBovs\-appctl\fR(8), limits the log level change to the specified module\[char46]
.IP \(bu
\fBsyslog\fR, \fBconsole\fR, or \fBfile\fR, to limit the log level change to only to the system log, to the console, or to a file, respectively\[char46] (If \fB\-\-detach\fR is specified, the daemon closes its standard file descriptors, so logging to the console will have no effect\[char46])
.IP
On Windows platform, \fBsyslog\fR is accepted as a word and is only useful along with the \fB\-\-syslog\-target\fR option (the word has no effect otherwise)\[char46]
.IP \(bu
\fBoff\fR, \fBemer\fR, \fBerr\fR, \fBwarn\fR, \fBinfo\fR, or \fBdbg\fR, to control the log level\[char46] Messages of the given severity or higher will be logged, and messages of lower severity will be filtered out\[char46] \fBoff\fR filters out all messages\[char46] See \fBovs\-appctl\fR(8) for a definition of each log level\[char46]
.RE
.IP
Case is not significant within \fIspec\fR\[char46]
.IP
Regardless of the log levels set for \fBfile\fR, logging to a file will not take place unless \fB\-\-log\-file\fR is also specified (see below)\[char46]
.IP
For compatibility with older versions of OVS, \fBany\fR is accepted as a word but has no effect\[char46]
.TP
\fB\-v\fR
.TQ .5in
\fB\-\-verbose\fR
Sets the maximum logging verbosity level, equivalent to \fB\-\-verbose=dbg\fR\[char46]
.TP
\fB\-vPATTERN:\fR\fIdestination\fR\fB:\fR\fIpattern\fR
.TQ .5in
\fB\-\-verbose=PATTERN:\fR\fIdestination\fR\fB:\fR\fIpattern\fR
Sets the log pattern for \fIdestination\fR to \fIpattern\fR\[char46] Refer to \fBovs\-appctl\fR(8) for a description of the valid syntax for \fIpattern\fR\[char46]
.TP
\fB\-vFACILITY:\fR\fIfacility\fR
.TQ .5in
\fB\-\-verbose=FACILITY:\fR\fIfacility\fR
Sets the RFC5424 facility of the log message\[char46] \fIfacility\fR can be one of \fBkern\fR, \fBuser\fR, \fBmail\fR, \fBdaemon\fR, \fBauth\fR, \fBsyslog\fR, \fBlpr\fR, \fBnews\fR, \fBuucp\fR, \fBclock\fR, \fBftp\fR, \fBntp\fR, \fBaudit\fR, \fBalert\fR, \fBclock2\fR, \fBlocal0\fR, \fBlocal1\fR, \fBlocal2\fR, \fBlocal3\fR, \fBlocal4\fR, \fBlocal5\fR, \fBlocal6\fR or \fBlocal7\fR\[char46] If this option is not specified, \fBdaemon\fR is used as the default for the local system syslog and \fBlocal0\fR is used while sending a message to the target provided via the \fB\-\-syslog\-target\fR option\[char46]
.TP
\fB\-\-log\-file\fR[\fB=\fR\fIfile\fR]
Enables logging to a file\[char46] If \fIfile\fR is specified, then it is used as the exact name for the log file\[char46] The default log file name used if \fIfile\fR is omitted is \fB/var/log/openvswitch/\fIprogram\fB\[char46]log\fR\[char46]
.TP
\fB\-\-syslog\-target=\fR\fIhost\fR\fB:\fR\fIport\fR
Send syslog messages to UDP \fIport\fR on \fIhost\fR, in addition to the system syslog\[char46] The \fIhost\fR must be a numerical IP address, not a hostname\[char46]
.TP
\fB\-\-syslog\-method=\fR\fImethod\fR
Specify \fImethod\fR as how syslog messages should be sent to syslog daemon\[char46] The following forms are supported:
.RS
.IP \(bu
\fBlibc\fR, to use the libc \fBsyslog()\fR function\[char46] Downside of using this options is that libc adds fixed prefix to every message before it is actually sent to the syslog daemon over \fB/dev/log\fR UNIX domain socket\[char46]
.IP \(bu
\fBunix:\fIfile\fB\fR, to use a UNIX domain socket directly\[char46] It is possible to specify arbitrary message format with this option\[char46] However, \fBrsyslogd 8\[char46]9\fR and older versions use hard coded parser function anyway that limits UNIX domain socket use\[char46] If you want to use arbitrary message format with older \fBrsyslogd\fR versions, then use UDP socket to localhost IP address instead\[char46]
.IP \(bu
\fBudp:\fIip\fB:\fIport\fB\fR, to use a UDP socket\[char46] With this method it is possible to use arbitrary message format also with older \fBrsyslogd\fR\[char46] When sending syslog messages over UDP socket extra precaution needs to be taken into account, for example, syslog daemon needs to be configured to listen on the specified UDP port, accidental iptables rules could be interfering with local syslog traffic and there are some security considerations that apply to UDP sockets, but do not apply to UNIX domain sockets\[char46]
.IP \(bu
\fBnull\fR, to discard all messages logged to syslog\[char46]
.RE
.IP
The default is taken from the \fBOVS_SYSLOG_METHOD\fR environment variable; if it is unset, the default is \fBlibc\fR\[char46]
.SS "PKI Options"
.PP
.PP
PKI configuration is required in order to use SSL for the connections to the Northbound and Southbound databases\[char46]
.RS
.TP
\fB\-p\fR \fIprivkey\[char46]pem\fR
.TQ .5in
\fB\-\-private\-key=\fR\fIprivkey\[char46]pem\fR
Specifies a PEM file containing the private key used as identity for outgoing SSL connections\[char46]
.TP
\fB\-c\fR \fIcert\[char46]pem\fR
.TQ .5in
\fB\-\-certificate=\fR\fIcert\[char46]pem\fR
Specifies a PEM file containing a certificate that certifies the private key specified on \fB\-p\fR or \fB\-\-private\-key\fR to be trustworthy\[char46] The certificate must be signed by the certificate authority (CA) that the peer in SSL connections will use to verify it\[char46]
.TP
\fB\-C\fR \fIcacert\[char46]pem\fR
.TQ .5in
\fB\-\-ca\-cert=\fR\fIcacert\[char46]pem\fR
Specifies a PEM file containing the CA certificate for verifying certificates presented to this program by SSL peers\[char46] (This may be the same certificate that SSL peers use to verify the certificate specified on \fB\-c\fR or \fB\-\-certificate\fR, or it may be a different one, depending on the PKI design in use\[char46])
.TP
\fB\-C none\fR
.TQ .5in
\fB\-\-ca\-cert=none\fR
Disables verification of certificates presented by SSL peers\[char46] This introduces a security risk, because it means that certificates cannot be verified to be those of known trusted hosts\[char46]
.RE
.RS
.TP
\fB\-\-bootstrap\-ca\-cert=\fR\fIcacert\[char46]pem\fR
When \fIcacert\[char46]pem\fR exists, this option has the same effect as \fB\-C\fR or \fB\-\-ca\-cert\fR\[char46] If it does not exist, then the executable will attempt to obtain the CA certificate from the SSL peer on its first SSL connection and save it to the named PEM file\[char46] If it is successful, it will immediately drop the connection and reconnect, and from then on all SSL connections must be authenticated by a certificate signed by the CA certificate thus obtained\[char46]
.IP
This option exposes the SSL connection to a man-in-the-middle attack obtaining the initial CA certificate, but it may be useful for bootstrapping\[char46]
.IP
This option is only useful if the SSL peer sends its CA certificate as part of the SSL certificate chain\[char46] The SSL protocol does not require the server to send the CA certificate\[char46]
.IP
This option is mutually exclusive with \fB\-C\fR and \fB\-\-ca\-cert\fR\[char46]
.RE
.RS
.TP
\fB\-\-peer\-ca\-cert=\fR\fIpeer-cacert\[char46]pem\fR
Specifies a PEM file that contains one or more additional certificates to send to SSL peers\[char46] \fIpeer-cacert\[char46]pem\fR should be the CA certificate used to sign the program\(cqs own certificate, that is, the certificate specified on \fB\-c\fR or \fB\-\-certificate\fR\[char46] If the program\(cqs certificate is self-signed, then \fB\-\-certificate\fR and \fB\-\-peer\-ca\-cert\fR should specify the same file\[char46]
.IP
This option is not useful in normal operation, because the SSL peer must already have the CA certificate for the peer to have any confidence in the program\(cqs identity\[char46] However, this offers a way for a new installation to bootstrap the CA certificate on its first SSL connection\[char46]
.RE
.SS "Other Options"
.TP
\fB\-h\fR
.TQ .5in
\fB\-\-help\fR
Prints a brief help message to the console\[char46]
.TP
\fB\-V\fR
.TQ .5in
\fB\-\-version\fR
Prints version information to the console\[char46]
.SH "CONFIGURATION"
.PP
.PP
\fBovn\-controller\fR retrieves most of its configuration information from the local Open vSwitch\(cqs ovsdb-server instance\[char46] The default location is \fBdb\[char46]sock\fR in the local Open vSwitch\(cqs \(dqrun\(dq directory\[char46] It may be overridden by specifying the \fIovs-database\fR argument as an OVSDB active or passive connection method, as described in \fBovsdb\fR(7)\[char46]
.PP
.PP
\fBovn\-controller\fR assumes it gets configuration information from the following keys in the \fBOpen_vSwitch\fR table of the local OVS instance:
.RS
.TP
\fBexternal_ids:system\-id\fR
The chassis name to use in the Chassis table\[char46]
.TP
\fBexternal_ids:hostname\fR
The hostname to use in the Chassis table\[char46]
.TP
\fBexternal_ids:ovn\-bridge\fR
The integration bridge to which logical ports are attached\[char46] The default is \fBbr\-int\fR\[char46] If this bridge does not exist when ovn-controller starts, it will be created automatically with the default configuration suggested in \fBovn\-architecture\fR(7)\[char46]
.TP
\fBexternal_ids:ovn\-remote\fR
The OVN database that this system should connect to for its configuration, in one of the same forms documented above for the \fIovs-database\fR\[char46]
.TP
\fBexternal_ids:ovn\-remote\-probe\-interval\fR
The inactivity probe interval of the connection to the OVN database, in milliseconds\[char46] If the value is zero, it disables the connection keepalive feature\[char46]
.IP
If the value is nonzero, then it will be forced to a value of at least 1000 ms\[char46]
.TP
\fBexternal_ids:ovn\-encap\-type\fR
The encapsulation type that a chassis should use to connect to this node\[char46] Multiple encapsulation types may be specified with a comma-separated list\[char46] Each listed encapsulation type will be paired with \fBovn\-encap\-ip\fR\[char46]
.IP
Supported tunnel types for connecting hypervisors are \fBgeneve\fR and \fBstt\fR\[char46] Gateways may use \fBgeneve\fR, \fBvxlan\fR, or \fBstt\fR\[char46]
.IP
Due to the limited amount of metadata in \fBvxlan\fR, the capabilities and performance of connected gateways will be reduced versus other tunnel formats\[char46]
.TP
\fBexternal_ids:ovn\-encap\-ip\fR
The IP address that a chassis should use to connect to this node using encapsulation types specified by \fBexternal_ids:ovn\-encap\-type\fR\[char46]
.TP
\fBexternal_ids:ovn\-bridge\-mappings\fR
A list of key-value pairs that map a physical network name to a local ovs bridge that provides connectivity to that network\[char46] An example value mapping two physical network names to two ovs bridges would be: \fBphysnet1:br\-eth0,physnet2:br\-eth1\fR\[char46]
.TP
\fBexternal_ids:ovn\-encap\-csum\fR
\fBovn\-encap\-csum\fR indicates that encapsulation checksums can be transmitted and received with reasonable performance\[char46] It is a hint to senders transmitting data to this chassis that they should use checksums to protect OVN metadata\[char46] Set to \fBtrue\fR to enable or \fBfalse\fR to disable\[char46] Depending on the capabilities of the network interface card, enabling encapsulation checksum may incur performance loss\[char46] In such cases, encapsulation checksums can be disabled\[char46]
.TP
\fBexternal_ids:ovn\-cms\-options\fR
A list of options that will be consumed by the CMS Plugin and which specific to this particular chassis\[char46] An example would be: \fBcms_option1,cms_option2:foo\fR\[char46]
.RE
.PP
.PP
\fBovn\-controller\fR reads the following values from the \fBOpen_vSwitch\fR database of the local OVS instance:
.RS
.TP
\fBdatapath\-type\fR from \fBBridge\fR table
This value is read from local OVS integration bridge row of \fBBridge\fR table and populated in \fBexternal_ids:datapath-type\fR of the \fBChassis\fR table in the OVN_Southbound database\[char46]
.TP
\fBiface\-types\fR from \fBOpen_vSwitch\fR table
This value is populated in \fBexternal_ids:iface-types\fR of the \fBChassis\fR table in the OVN_Southbound database\[char46]
.TP
\fBprivate_key\fR, \fBcertificate\fR, \fBca_cert\fR, and \fBbootstrap_ca_cert\fR from \fBSSL\fR table
These values provide the SSL configuration used for connecting to the OVN southbound database server when an SSL connection type is configured via \fBexternal_ids:ovn\-remote\fR\[char46] Note that this SSL configuration can also be provided via command-line options, the configuration in the database takes precedence if both are present\[char46]
.RE
.SH "OPEN VSWITCH DATABASE USAGE"
.PP
.PP
\fBovn\-controller\fR uses a number of \fBexternal_ids\fR keys in the Open vSwitch database to keep track of ports and interfaces\[char46] For proper operation, users should not change or clear these keys:
.RS
.TP
\fBexternal_ids:ovn\-chassis\-id\fR in the \fBPort\fR table
The presence of this key identifies a tunnel port within the integration bridge as one created by \fBovn\-controller\fR to reach a remote chassis\[char46] Its value is the chassis ID of the remote chassis\[char46]
.TP
\fBexternal_ids:ct\-zone\-*\fR in the \fBBridge\fR table
Logical ports and gateway routers are assigned a connection tracking zone by \fBovn\-controller\fR for stateful services\[char46] To keep state across restarts of \fBovn\-controller\fR, these keys are stored in the integration bridge\(cqs Bridge table\[char46] The name contains a prefix of \fBct\-zone\-\fR followed by the name of the logical port or gateway router\(cqs zone key\[char46] The value for this key identifies the zone used for this port\[char46]
.TP
\fBexternal_ids:ovn\-localnet\-port\fR in the \fBPort\fR table
The presence of this key identifies a patch port as one created by \fBovn\-controller\fR to connect the integration bridge and another bridge to implement a \fBlocalnet\fR logical port\[char46] Its value is the name of the logical port with \fBtype\fR set to \fBlocalnet\fR that the port implements\[char46] See \fBexternal_ids:ovn\-bridge\-mappings\fR, above, for more information\[char46]
.IP
Each \fBlocalnet\fR logical port is implemented as a pair of patch ports, one in the integration bridge, one in a different bridge, with the same \fBexternal_ids:ovn\-localnet\-port\fR value\[char46]
.TP
\fBexternal_ids:ovn\-l2gateway\-port\fR in the \fBPort\fR table
The presence of this key identifies a patch port as one created by \fBovn\-controller\fR to connect the integration bridge and another bridge to implement a \fBl2gateway\fR logical port\[char46] Its value is the name of the logical port with \fBtype\fR set to \fBl2gateway\fR that the port implements\[char46] See \fBexternal_ids:ovn\-bridge\-mappings\fR, above, for more information\[char46]
.IP
Each \fBl2gateway\fR logical port is implemented as a pair of patch ports, one in the integration bridge, one in a different bridge, with the same \fBexternal_ids:ovn\-l2gateway\-port\fR value\[char46]
.TP
\fBexternal\-ids:ovn\-l3gateway\-port\fR in the \fBPort\fR table
This key identifies a patch port as one created by \fBovn\-controller\fR to implement a \fBl3gateway\fR logical port\[char46] Its value is the name of the logical port with type set to \fBl3gateway\fR\[char46] This patch port is similar to the OVN logical patch port, except that \fBl3gateway\fR port can only be bound to a paticular chassis\[char46]
.TP
\fBexternal\-ids:ovn\-logical\-patch\-port\fR in the \fBPort\fR table
This key identifies a patch port as one created by \fBovn\-controller\fR to implement an OVN logical patch port within the integration bridge\[char46] Its value is the name of the OVN logical patch port that it implements\[char46]
.RE
.SH "OVN SOUTHBOUND DATABASE USAGE"
.PP
.PP
\fBovn\-controller\fR reads from much of the \fBOVN_Southbound\fR database to guide its operation\[char46] \fBovn\-controller\fR also writes to the following tables:
.RS
.TP
\fBChassis\fR
Upon startup, \fBovn\-controller\fR creates a row in this table to represent its own chassis\[char46] Upon graceful termination, e\[char46]g\[char46] with \fBovs\-appctl \-t ovn\-controller exit\fR (but not \fBSIGTERM\fR), \fBovn\-controller\fR removes its row\[char46]
.TP
\fBEncap\fR
Upon startup, \fBovn\-controller\fR creates a row or rows in this table that represent the tunnel encapsulations by which its chassis can be reached, and points its \fBChassis\fR row to them\[char46] Upon graceful termination, \fBovn\-controller\fR removes these rows\[char46]
.TP
\fBPort_Binding\fR
At runtime, \fBovn\-controller\fR sets the \fBchassis\fR columns of ports that are resident on its chassis to point to its \fBChassis\fR row, and, conversely, clears the \fBchassis\fR column of ports that point to its \fBChassis\fR row but are no longer resident on its chassis\[char46] The \fBchassis\fR column has a weak reference type, so when \fBovn\-controller\fR gracefully exits and removes its \fBChassis\fR row, the database server automatically clears any remaining references to that row\[char46]
.TP
\fBMAC_Binding\fR
At runtime, \fBovn\-controller\fR updates the \fBMAC_Binding\fR table as instructed by \fBput_arp\fR and \fBput_nd\fR logical actions\[char46] These changes persist beyond the lifetime of \fBovn\-controller\fR\[char46]
.RE
.SH "RUNTIME MANAGEMENT COMMANDS"
.PP
.PP
\fBovs\-appctl\fR can send commands to a running \fBovn\-controller\fR process\[char46] The currently supported commands are described below\[char46]
.RS
.TP
\fBexit\fR
Causes \fBovn\-controller\fR to gracefully terminate\[char46]
.TP
\fBct\-zone\-list\fR
Lists each local logical port and its connection tracking zone\[char46]
.TP
\fBmeter\-table\-list\fR
Lists each meter table entry and its local meter id\[char46]
.TP
\fBgroup\-table\-list\fR
Lists each group table entry and its local group id\[char46]
.TP
\fBinject\-pkt\fR \fImicroflow\fR
Injects \fImicroflow\fR into the connected Open vSwitch instance\[char46] \fImicroflow\fR must contain an ingress logical port (\fBinport\fR argument) that is present on the Open vSwitch instance\[char46]
.IP
The \fImicroflow\fR argument describes the packet whose forwarding is to be simulated, in the syntax of an OVN logical expression, as described in \fBovn\-sb\fR(5), to express constraints\[char46] The parser understands prerequisites; for example, if the expression refers to \fBip4\[char46]src\fR, there is no need to explicitly state \fBip4\fR or \fBeth\[char46]type ==
0x800\fR\[char46]
.TP
\fBconnection\-status\fR
Show OVN SBDB connection status for the chassis\[char46]
.RE
