'\" p
.\" -*- nroff -*-
.TH "ovn-nb" 5 " DB Schema 3.2.0" "Open vSwitch 2.5.90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH NAME
ovn-nb \- OVN_Northbound database schema
.PP
This database is the interface between OVN and the cloud management system
(CMS), such as OpenStack, running above it\[char46]  The CMS produces almost all of
the contents of the database\[char46]  The \fBovn\-northd\fR program
monitors the database contents, transforms it, and stores it into the \fBOVN_Southbound\fR database\[char46]
.PP
We generally speak of ``the\(cq\(cq CMS, but one can imagine scenarios in
which multiple CMSes manage different parts of an OVN deployment\[char46]
.SS "External IDs"
.PP
Each of the tables in this database contains a special column, named
\fBexternal_ids\fR\[char46]  This column has the same form and purpose each
place it appears\[char46]
.RS
.TP
\fBexternal_ids\fR: map of string-string pairs
Key-value pairs for use by the CMS\[char46]  The CMS might use certain pairs, for
example, to identify entities in its own configuration that correspond to
those in this database\[char46]
.RE
.SH "TABLE SUMMARY"
.PP
The following list summarizes the purpose of each of the tables in the
\fBOVN_Northbound\fR database.  Each table is described in more detail on a later
page.
.IP "Table" 1in
Purpose
.TQ 1in
\fBLogical_Switch\fR
L2 logical switch
.TQ 1in
\fBLogical_Switch_Port\fR
L2 logical switch port
.TQ 1in
\fBAddress_Set\fR
Address Sets
.TQ 1in
\fBLoad_Balancer\fR
load balancer
.TQ 1in
\fBACL\fR
Access Control List (ACL) rule
.TQ 1in
\fBLogical_Router\fR
L3 logical router
.TQ 1in
\fBLogical_Router_Port\fR
L3 logical router port
.TQ 1in
\fBLogical_Router_Static_Route\fR
Logical router static routes
.TQ 1in
\fBNAT\fR
NAT rules for a Gateway router\[char46]
.\" check if in troff mode (TTY)
.if t \{
.bp
.SH "TABLE RELATIONSHIPS"
.PP
The following diagram shows the relationship among tables in the
database.  Each node represents a table.  Tables that are part of the
``root set'' are shown with double borders.  Each edge leads from the
table that contains it and points to the table that its value
represents.  Edges are labeled with their column names, followed by a
constraint on the number of allowed values: \fB?\fR for zero or one,
\fB*\fR for zero or more, \fB+\fR for one or more.  Thick lines
represent strong references; thin lines represent weak references.
.RS -1in
.ps -3
.PS
linethick = 1;
linethick = 0.5;
box at 4.039262206,1.647065 wid 1.2941225 height 0.47059 "Load_Balancer"
box at 4.039262206,1.647065 wid 1.23856694444444 height 0.415034444444444
linethick = 1;
box at 4.039262206,0.94118 wid 1.712382892 height 0.47059 "Logical_Switch_Port"
linethick = 0.5;
box at 0.6666660294,2.0000075 wid 1.111157108 height 0.47059 "Address_Set"
box at 0.6666660294,2.0000075 wid 1.05560155244444 height 0.415034444444444
linethick = 0.5;
box at 0.6666660294,0.94118 wid 1.333369706 height 0.47059 "Logical_Switch"
box at 0.6666660294,0.94118 wid 1.27781415044444 height 0.415034444444444
linethick = 1;
box at 4.039262206,0.235295 wid 0.705885 height 0.47059 "ACL"
linethick = 1;
box at 4.039262206,3.76472 wid 2.326785196 height 0.47059 "Logical_Router_Static_Route"
linethick = 1;
box at 4.039262206,3.058835 wid 1.712382892 height 0.47059 "Logical_Router_Port"
linethick = 0.5;
box at 0.6666660294,3.058835 wid 1.320287304 height 0.47059 "Logical_Router"
box at 0.6666660294,3.058835 wid 1.26473174844444 height 0.415034444444444
linethick = 1;
box at 4.039262206,2.35295 wid 0.705885 height 0.47059 "NAT"
linethick = 1;
spline -> from 1.333369706,1.130921888 to 1.333369706,1.130921888 to 1.412428826,1.151721966 to 1.492146772,1.1717691 to 1.568664706,1.189557402 to 2.183725836,1.332428526 to 2.893469674,1.46071136 to 3.391636248,1.544758734
"load_balancer?" at 2.104572598,1.496758554
linethick = 1;
spline -> from 1.336852072,0.94118 to 1.336852072,0.94118 to 1.864195226,0.94118 to 2.60800978,0.94118 to 3.179870748,0.94118
"ports*" at 2.104572598,1.039250956
linethick = 1;
spline -> from 1.333369706,0.7514757592 to 1.333369706,0.7514757592 to 1.412428826,0.7306474458 to 1.492146772,0.7105814882 to 1.568664706,0.6928120098 to 2.316902806,0.5189948874 to 3.20518849,0.3668154932 to 3.682272632,0.2894504972
"acls*" at 2.104572598,0.7908547304
linethick = 1;
spline -> from 1.328569688,3.247259236 to 1.328569688,3.247259236 to 1.409134696,3.268529904 to 1.490640884,3.289047628 to 1.568664706,3.307212402 to 1.991348644,3.405377476 to 2.45883275,3.496671936 to 2.87154018,3.571495746
"static_routes*" at 2.104572598,3.614413554
linethick = 1;
spline -> from 1.32894616,3.058835 to 1.32894616,3.058835 to 1.857324612,3.058835 to 2.6070686,3.058835 to 3.182035462,3.058835
"ports*" at 2.104572598,3.156905956
linethick = 1;
spline -> from 1.328569688,2.870410764 to 1.328569688,2.870410764 to 1.409134696,2.849140096 to 1.490640884,2.828622372 to 1.568664706,2.810457598 to 2.316902806,2.636621652 to 3.20518849,2.484432846 to 3.682272632,2.40706785
"nat*" at 2.104572598,2.908528554
.ps +3
.PE
.RE\}
.bp
.SH "Logical_Switch TABLE"
Each row represents one L2 logical switch\[char46]
.PP
There are two kinds of logical switches, that is, ones that fully
virtualize the network (overlay logical switches) and ones that provide
simple connectivity to a physical network (bridged logical switches)\[char46]
They work in the same way when providing connectivity between logical
ports on same chasis, but differently when connecting remote logical
ports\[char46]  Overlay logical switches connect remote logical ports by tunnels,
while bridged logical switches provide connectivity to remote ports by
bridging the packets to directly connected physical L2 segment with the
help of \fBlocalnet\fR ports\[char46]  Each bridged logical switch has
one and only one \fBlocalnet\fR port, which has only one special
address \fBunknown\fR\[char46]
.SS "Summary:
.TQ 3.00in
\fBname\fR
string
.TQ 3.00in
\fBports\fR
set of \fBLogical_Switch_Port\fRs
.TQ 3.00in
\fBload_balancer\fR
optional \fBLoad_Balancer\fR
.TQ 3.00in
\fBacls\fR
set of \fBACL\fRs
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBname\fR: string"
A name for the logical switch\[char46]  This name has no special meaning or purpose
other than to provide convenience for human interaction with the ovn-nb
database\[char46]  There is no requirement for the name to be unique\[char46]  The
logical switch\(cqs UUID should be used as the unique identifier\[char46]
.IP "\fBports\fR: set of \fBLogical_Switch_Port\fRs"
The logical ports connected to the logical switch\[char46]
.IP
It is an error for multiple logical switches to include the same
logical port\[char46]
.IP "\fBload_balancer\fR: optional \fBLoad_Balancer\fR"
Load balance a virtual ipv4 address to a set of logical port endpoint
ipv4 addresses\[char46]
.IP "\fBacls\fR: set of \fBACL\fRs"
Access control rules that apply to packets within the logical switch\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Logical_Switch_Port TABLE"
A port within an L2 logical switch\[char46]
.SS "Summary:
.TQ .25in
\fICore Features:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBtype\fR
string
.RE
.TQ .25in
\fIOptions:\fR
.RS .25in
.TQ 2.75in
\fBoptions\fR
map of string-string pairs
.TQ .25in
\fIOptions for router ports:\fR
.RS .25in
.TQ 2.50in
\fBoptions : router-port\fR
optional string
.RE
.TQ .25in
\fIOptions for localnet ports:\fR
.RS .25in
.TQ 2.50in
\fBoptions : network_name\fR
optional string
.RE
.TQ .25in
\fIOptions for l2gateway ports:\fR
.RS .25in
.TQ 2.50in
\fBoptions : network_name\fR
optional string
.RE
.TQ .25in
\fIOptions for vtep ports:\fR
.RS .25in
.TQ 2.50in
\fBoptions : vtep-physical-switch\fR
optional string
.TQ 2.50in
\fBoptions : vtep-logical-switch\fR
optional string
.RE
.TQ .25in
\fIVMI (or VIF) Options:\fR
.RS .25in
.TQ 2.50in
\fBoptions : policing_rate\fR
optional string
.TQ 2.50in
\fBoptions : policing_burst\fR
optional string
.RE
.RE
.TQ .25in
\fIContainers:\fR
.RS .25in
.TQ 2.75in
\fBparent_name\fR
optional string
.TQ 2.75in
\fBtag\fR
optional integer, in range 1 to 4,095
.RE
.TQ .25in
\fIPort State:\fR
.RS .25in
.TQ 2.75in
\fBup\fR
optional boolean
.TQ 2.75in
\fBenabled\fR
optional boolean
.RE
.TQ .25in
\fIAddressing:\fR
.RS .25in
.TQ 2.75in
\fBaddresses\fR
set of strings
.TQ 2.75in
\fBport_security\fR
set of strings
.RE
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.ST "Core Features:"
.IP "\fBname\fR: string (must be unique within table)"
The logical port name\[char46]
.IP
For entities (VMs or containers) that are spawned in the hypervisor,
the name used here must match those used in the \fBexternal_ids:iface-id\fR in the
\fBOpen_vSwitch\fR database\(cqs \fBInterface\fR table, because hypervisors use \fBexternal_ids:iface-id\fR as a lookup
key to identify the network interface of that entity\[char46]
.IP
For containers that share a VIF within a VM, the name can be any
unique identifier\[char46]  See \fBContainers\fR, below, for more
information\[char46]
.IP "\fBtype\fR: string"
Specify a type for this logical port\[char46]  Logical ports can be used to
model other types of connectivity into an OVN logical switch\[char46]  The
following types are defined:
.RS
.TP
(empty string)
A VM (or VIF) interface\[char46]
.TP
\fBrouter\fR
A connection to a logical router\[char46]
.TP
\fBlocalnet\fR
A connection to a locally accessible network from each
\fBovn\-controller\fR instance\[char46]  A logical switch can only
have a single \fBlocalnet\fR port attached\[char46]  This is used
to model direct connectivity to an existing network\[char46]
.TP
\fBl2gateway\fR
A connection to a physical network\[char46]
.TP
\fBvtep\fR
A port to a logical switch on a VTEP gateway\[char46]
.RE
.ST "Options:"
.IP "\fBoptions\fR: map of string-string pairs"
This column provides key/value settings specific to the logical port
\fBtype\fR\[char46]  The type-specific options are described
individually below\[char46]
.ST "Options for router ports:"
These options apply when \fBtype\fR is \fBrouter\fR\[char46]
.IP "\fBoptions : router-port\fR: optional string"
Required\[char46]  The \fBname\fR of the \fBLogical_Router_Port\fR to which this logical switch port is
connected\[char46]
.ST "Options for localnet ports:"
These options apply when \fBtype\fR is
\fBlocalnet\fR\[char46]
.IP "\fBoptions : network_name\fR: optional string"
Required\[char46]  The name of the network to which the \fBlocalnet\fR
port is connected\[char46]  Each hypervisor, via \fBovn\-controller\fR,
uses its local configuration to determine exactly how to connect to
this locally accessible network\[char46]
.ST "Options for l2gateway ports:"
These options apply when \fBtype\fR is
\fBl2gateway\fR\[char46]
.IP "\fBoptions : network_name\fR: optional string"
Required\[char46]  The name of the network to which the \fBl2gateway\fR
port is connected\[char46]  The L2 gateway, via \fBovn\-controller\fR,
uses its local configuration to determine exactly how to connect to
this network\[char46]
.ST "Options for vtep ports:"
These options apply when \fBtype\fR is \fBvtep\fR\[char46]
.IP "\fBoptions : vtep-physical-switch\fR: optional string"
Required\[char46]  The name of the VTEP gateway\[char46]
.IP "\fBoptions : vtep-logical-switch\fR: optional string"
Required\[char46]  A logical switch name connected by the VTEP gateway\[char46]
.ST "VMI (or VIF) Options:"
These options apply to logical ports with \fBtype\fR having
(empty string)
.IP "\fBoptions : policing_rate\fR: optional string"
If set, indicates the maximum rate for data sent from this interface,
in kbps\[char46] Data exceeding this rate is dropped\[char46]
.IP "\fBoptions : policing_burst\fR: optional string"
If set, indicates the maximum burst size for data sent from this
interface, in kb\[char46]
.ST "Containers:"
When a large number of containers are nested within a VM, it may be too
expensive to dedicate a VIF to each container\[char46]  OVN can use VLAN tags
to support such cases\[char46]  Each container is assigned a VLAN ID and each
packet that passes between the hypervisor and the VM is tagged with the
appropriate ID for the container\[char46]  Such VLAN IDs never appear on a
physical wire, even inside a tunnel, so they need not be unique except
relative to a single VM on a hypervisor\[char46]
.PP
These columns are used for VIFs that represent nested containers using
shared VIFs\[char46]  For VMs and for containers that have dedicated VIFs, they
are empty\[char46]
.IP "\fBparent_name\fR: optional string"
The VM interface through which the nested container sends its network
traffic\[char46]  This must match the \fBname\fR column for some
other \fBLogical_Switch_Port\fR\[char46]
.IP "\fBtag\fR: optional integer, in range 1 to 4,095"
The VLAN tag in the network traffic associated with a container\(cqs
network interface\[char46]
.IP
When \fBtype\fR is set to \fBlocalnet\fR, this can
be set to indicate that the port represents a connection to a
specific VLAN on a locally accessible network\[char46] The VLAN ID is used to
match incoming traffic and is also added to outgoing traffic\[char46]
.ST "Port State:"
.IP "\fBup\fR: optional boolean"
This column is populated by \fBovn\-northd\fR, rather than by the
CMS plugin as is most of this database\[char46]  When a logical port is bound
to a physical location in the OVN Southbound database \fBBinding\fR table, \fBovn\-northd\fR
sets this column to \fBtrue\fR; otherwise, or if the port
becomes unbound later, it sets it to \fBfalse\fR\[char46]  This allows
the CMS to wait for a VM\(cqs (or container\(cqs) networking to become active
before it allows the VM (or container) to start\[char46]
.IP "\fBenabled\fR: optional boolean"
This column is used to administratively set port state\[char46]  If this column
is empty or is set to \fBtrue\fR, the port is enabled\[char46]  If this
column is set to \fBfalse\fR, the port is disabled\[char46]  A disabled
port has all ingress and egress traffic dropped\[char46]
.ST "Addressing:"
.IP "\fBaddresses\fR: set of strings"
Addresses owned by the logical port\[char46]
.IP
Each element in the set must take one of the following forms:
.RS
.TP
\fBEthernet address followed by zero or more IPv4 or IPv6 addresses (or both)\fR
An Ethernet address defined is owned by the logical port\[char46]
Like a physical Ethernet NIC, a logical port ordinarily has
a single fixed Ethernet address\[char46]
.IP
When a OVN logical switch processes a unicast Ethernet frame
whose destination MAC address is in a logical port\(cqs \fBaddresses\fR column, it delivers it only to that port, as
if a MAC learning process had learned that MAC address on the
port\[char46]
.IP
If IPv4 or IPv6 address(es) (or both) are defined, it indicates
that the logical port owns the given IP addresses\[char46]
.IP
If IPv4 address(es) are defined, the OVN logical switch uses this
information to synthesize responses to ARP requests without
traversing the physical network\[char46] The OVN logical router connected
to the logical switch, if any, uses this information to avoid
issuing ARP requests for logical switch ports\[char46]
.IP
Note that the order here is important\[char46] The Ethernet address must
be listed before the IP address(es) if defined\[char46]
.IP
Examples:
.RS
.TP
\fB80:fa:5b:06:72:b7\fR
This indicates that the logical port owns the above mac address\[char46]
.TP
\fB80:fa:5b:06:72:b7 10\[char46]0\[char46]0\[char46]4 20\[char46]0\[char46]0\[char46]4\fR
This indicates that the logical port owns the mac address and two
IPv4 addresses\[char46]
.TP
\fB80:fa:5b:06:72:b7 fdaa:15f2:72cf:0:f816:3eff:fe20:3f41\fR
This indicates that the logical port owns the mac address and
1 IPv6 address\[char46]
.TP
\fB80:fa:5b:06:72:b7 10\[char46]0\[char46]0\[char46]4 fdaa:15f2:72cf:0:f816:3eff:fe20:3f41\fR
This indicates that the logical port owns the mac address and
1 IPv4 address and 1 IPv6 address\[char46]
.RE
.TP
\fBunknown\fR
This indicates that the logical port has an unknown set of Ethernet
addresses\[char46]  When an OVN logical switch processes a unicast Ethernet
frame whose destination MAC address is not in any logical port\(cqs
\fBaddresses\fR column, it delivers it to the port (or
ports) whose \fBaddresses\fR columns include
\fBunknown\fR\[char46]
.RE
.IP "\fBport_security\fR: set of strings"
This column controls the addresses from which the host attached to the
logical port (``the host\(cq\(cq) is allowed to send packets and to which it
is allowed to receive packets\[char46]  If this column is empty, all addresses
are permitted\[char46]
.IP
Each element in the set must begin with one Ethernet address\[char46]
This would restrict the host to sending packets from and receiving
packets to the ethernet addresses defined in the logical port\(cqs
\fBport_security\fR column\[char46] It also restricts the inner
source MAC addresses that the host may send in ARP and IPv6
Neighbor Discovery packets\[char46] The host is always allowed to receive packets
to multicast and broadcast Ethernet addresses\[char46]
.IP
Each element in the set may additionally contain one or more IPv4 or
IPv6 addresses (or both), with optional masks\[char46]  If a mask is given, it
must be a CIDR mask\[char46]  In addition to the restrictions described for
Ethernet addresses above, such an element restricts the IPv4 or IPv6
addresses from which the host may send and to which it may receive
packets to the specified addresses\[char46]  A masked address, if the host part
is zero, indicates that the host is allowed to use any address in the
subnet; if the host part is nonzero, the mask simply indicates the size
of the subnet\[char46] In addition:
.RS
.IP \(bu
If any IPv4 address is given, the host is also allowed to receive
packets to the IPv4 local broadcast address 255\[char46]255\[char46]255\[char46]255 and to
IPv4 multicast addresses (224\[char46]0\[char46]0\[char46]0/4)\[char46]  If an IPv4 address with a
mask is given, the host is also allowed to receive packets to the
broadcast address in that specified subnet\[char46]
.IP
If any IPv4 address is given, the host is additionally restricted
to sending ARP packets with the specified source IPv4 address\[char46]
(RARP is not restricted\[char46])
.IP \(bu
If any IPv6 address is given, the host is also allowed to receive
packets to IPv6 multicast addresses (ff00::/8)\[char46]
.IP
If any IPv6 address is given, the host is additionally restricted
to sending IPv6 Neighbor Discovery Solicitation or Advertisement
packets with the specified source address or, for solicitations,
the unspecified address\[char46]
.RE
.IP
If an element includes an IPv4 address, but no IPv6 addresses, then
IPv6 traffic is not allowed\[char46]  If an element includes an IPv6 address,
but no IPv4 address, then IPv4 and ARP traffic is not allowed\[char46]
.IP
This column uses the same lexical syntax as the \fBmatch\fR column in the OVN Southbound
database\(cqs \fBPipeline\fR table\[char46]  Multiple
addresses within an element may be space or comma separated\[char46]
.IP
This column is provided as a convenience to cloud management systems,
but all of the features that it implements can be implemented as ACLs
using the \fBACL\fR table\[char46]
.IP
Examples:
.RS
.TP
\fB80:fa:5b:06:72:b7\fR
The host may send traffic from and receive traffic to the specified
MAC address, and to receive traffic to Ethernet multicast and
broadcast addresses, but not otherwise\[char46]  The host may not send ARP or
IPv6 Neighbor Discovery packets with inner source Ethernet addresses
other than the one specified\[char46]
.TP
\fB80:fa:5b:06:72:b7 192\[char46]168\[char46]1\[char46]10/24\fR
This adds further restrictions to the first example\[char46]  The host may
send IPv4 packets from or receive IPv4 packets to only 192\[char46]168\[char46]1\[char46]10,
except that it may also receive IPv4 packets to 192\[char46]168\[char46]1\[char46]255 (based
on the subnet mask), 255\[char46]255\[char46]255\[char46]255, and any address in 224\[char46]0\[char46]0\[char46]0/4\[char46]
The host may not send ARPs with a source Ethernet address other than
80:fa:5b:06:72:b7 or source IPv4 address other than 192\[char46]168\[char46]1\[char46]10\[char46]
The host may not send or receive any IPv6 (including IPv6 Neighbor
Discovery) traffic\[char46]
.TP
\fB\(dq80:fa:5b:12:42:ba\(dq, \(dq80:fa:5b:06:72:b7 192\[char46]168\[char46]1\[char46]10/24\(dq\fR
The host may send traffic from and receive traffic to the
specified MAC addresses, and
to receive traffic to Ethernet multicast and broadcast addresses,
but not otherwise\[char46]   With MAC 80:fa:5b:12:42:ba, the host may
send traffic from and receive traffic to any L3 address\[char46]
With MAC 80:fa:5b:06:72:b7, the host may send IPv4 packets from or
receive IPv4 packets to only 192\[char46]168\[char46]1\[char46]10, except that it may also
receive IPv4 packets to 192\[char46]168\[char46]1\[char46]255 (based on the subnet mask),
255\[char46]255\[char46]255\[char46]255, and any address in 224\[char46]0\[char46]0\[char46]0/4\[char46]  The host may not
send or receive any IPv6 (including IPv6 Neighbor Discovery) traffic\[char46]
.RE
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Address_Set TABLE"
Each row in this table represents a named set of addresses\[char46]
An address set may contain Ethernet, IPv4, or IPv6 addresses
with optional bitwise or CIDR masks\[char46]
Address set may ultimately be used in ACLs to compare against
fields such as \fBip4\[char46]src\fR or \fBip6\[char46]src\fR\[char46]
A single address set must contain addresses of the
same type\[char46] As an example, the following would create an address set
with three IP addresses:
.PP
.nf
\fB
.br
\fB      ovn\-nbctl create Address_Set name=set1 addresses=\(cq10\[char46]0\[char46]0\[char46]1 10\[char46]0\[char46]0\[char46]2 10\[char46]0\[char46]0\[char46]3\(cq
.br
\fB
.fi
.PP
Address sets may be used in the \fBmatch\fR column
of the \fBACL\fR table\[char46]  For syntax information, see the details
of the expression language used for the \fBmatch\fR column in the \fBLogical_Flow\fR table of the \fBOVN_Southbound\fR database\[char46]
.SS "Summary:
.TQ 3.00in
\fBname\fR
string (must be unique within table)
.TQ 3.00in
\fBaddresses\fR
set of strings
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBname\fR: string (must be unique within table)"
A name for the address set\[char46]  This must be unique among all address sets\[char46]
.IP "\fBaddresses\fR: set of strings"
The set of addresses in string form\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Load_Balancer TABLE"
Each row represents one load balancer\[char46]
.SS "Summary:
.TQ 3.00in
\fBvips\fR
map of string-string pairs
.TQ 3.00in
\fBprotocol\fR
optional string, either \fBudp\fR or \fBtcp\fR
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBvips\fR: map of string-string pairs"
A map of virtual IPv4 addresses (and an optional port number with
\fB:\fR as a separator) associated with this load balancer and
their corresponding endpoint IPv4 addresses (and optional port numbers
with \fB:\fR as separators) separated by commas\[char46]  If
the destination IP address (and port number) of a packet leaving a
container or a VM matches the virtual IPv4 address (and port number)
provided here as a key, then OVN will statefully replace the
destination IP address by one of the provided IPv4 address (and port
number) in this map as a value\[char46]  Examples for keys are \(dq192\[char46]168\[char46]1\[char46]4\(dq
and \(dq172\[char46]16\[char46]1\[char46]8:80\(dq\[char46]  Examples for value are \(dq10\[char46]0\[char46]0\[char46]1, 10\[char46]0\[char46]0\[char46]2\(dq and
\(dq20\[char46]0\[char46]0\[char46]10:8800, 20\[char46]0\[char46]0\[char46]11:8800\(dq\[char46]
.IP "\fBprotocol\fR: optional string, either \fBudp\fR or \fBtcp\fR"
Valid protocols are \fBtcp\fR or \fBudp\fR\[char46]  This column
is useful when a port number is provided as part of the
\fBvips\fR column\[char46]  If this column is empty and a port number
is provided as part of \fBvips\fR column, OVN assumes the
protocol to be \fBtcp\fR\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "ACL TABLE"
Each row in this table represents one ACL rule for a logical switch
that points to it through its \fBacls\fR column\[char46]  The \fBaction\fR column for the highest-\fBpriority\fR
matching row in this table determines a packet\(cqs treatment\[char46]  If no row
matches, packets are allowed by default\[char46]  (Default-deny treatment is
possible: add a rule with \fBpriority\fR 0, \fB0\fR as
\fBmatch\fR, and \fBdeny\fR as \fBaction\fR\[char46])
.SS "Summary:
.TQ 3.00in
\fBpriority\fR
integer, in range 0 to 32,767
.TQ 3.00in
\fBdirection\fR
string, either \fBto\-lport\fR or \fBfrom\-lport\fR
.TQ 3.00in
\fBmatch\fR
string
.TQ 3.00in
\fBaction\fR
string, one of \fBallow\-related\fR, \fBdrop\fR, \fBallow\fR, or \fBreject\fR
.TQ 3.00in
\fBlog\fR
boolean
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBpriority\fR: integer, in range 0 to 32,767"
The ACL rule\(cqs priority\[char46]  Rules with numerically higher priority
take precedence over those with lower\[char46]  If two ACL rules with
the same priority both match, then the one actually applied to a
packet is undefined\[char46]
.IP
Return traffic from an \fBallow\-related\fR flow is always
allowed and cannot be changed through an ACL\[char46]
.IP "\fBdirection\fR: string, either \fBto\-lport\fR or \fBfrom\-lport\fR"
Direction of the traffic to which this rule should apply:
.RS
.IP \(bu
\fBfrom\-lport\fR: Used to implement filters on traffic
arriving from a logical port\[char46]  These rules are applied to the
logical switch\(cqs ingress pipeline\[char46]
.IP \(bu
\fBto\-lport\fR: Used to implement filters on traffic
forwarded to a logical port\[char46]  These rules are applied to the
logical switch\(cqs egress pipeline\[char46]
.RE
.IP "\fBmatch\fR: string"
The packets that the ACL should match, in the same expression
language used for the \fBmatch\fR column in the OVN Southbound database\(cqs
\fBLogical_Flow\fR table\[char46]  The
\fBoutport\fR logical port is only available in the
\fBto\-lport\fR direction (the \fBinport\fR is
available in both directions)\[char46]
.IP
By default all traffic is allowed\[char46]  When writing a more
restrictive policy, it is important to remember to allow flows
such as ARP and IPv6 neighbor discovery packets\[char46]
.IP
Note that you can not create an ACL matching on a port with
type=router\[char46]
.IP
Note that when \fBlocalnet\fR port exists in a lswitch, for
\fBto\-lport\fR direction, the \fBinport\fR works only if
the \fBto\-lport\fR is located on the same chassis as the
\fBinport\fR\[char46]
.IP "\fBaction\fR: string, one of \fBallow\-related\fR, \fBdrop\fR, \fBallow\fR, or \fBreject\fR"
The action to take when the ACL rule matches:
.RS
.IP \(bu
\fBallow\fR: Forward the packet\[char46]
.IP \(bu
\fBallow\-related\fR: Forward the packet and related traffic
(e\[char46]g\[char46] inbound replies to an outbound connection)\[char46]
.IP \(bu
\fBdrop\fR: Silently drop the packet\[char46]
.IP \(bu
\fBreject\fR: Drop the packet, replying with a RST for TCP or
ICMP unreachable message for other IP-based protocols\[char46]
\fBNot implemented\-\-currently treated as drop\fR
.RE
.IP "\fBlog\fR: boolean"
If set to \fBtrue\fR, packets that match the ACL will trigger a
log message on the transport node or nodes that perform ACL processing\[char46]
Logging may be combined with any \fBaction\fR\[char46]
.IP
Logging is not yet implemented\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Logical_Router TABLE"
Each row represents one L3 logical router\[char46]
.SS "Summary:
.TQ 3.00in
\fBname\fR
string
.TQ 3.00in
\fBports\fR
set of \fBLogical_Router_Port\fRs
.TQ 3.00in
\fBstatic_routes\fR
set of \fBLogical_Router_Static_Route\fRs
.TQ 3.00in
\fBdefault_gw\fR
optional string
.TQ 3.00in
\fBenabled\fR
optional boolean
.TQ 3.00in
\fBnat\fR
set of \fBNAT\fRs
.TQ .25in
\fIOptions:\fR
.RS .25in
.TQ 2.75in
\fBoptions : chassis\fR
optional string
.RE
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBname\fR: string"
A name for the logical router\[char46]  This name has no special meaning or purpose
other than to provide convenience for human interaction with the ovn-nb
database\[char46]  There is no requirement for the name to be unique\[char46]  The
logical router\(cqs UUID should be used as the unique identifier\[char46]
.IP "\fBports\fR: set of \fBLogical_Router_Port\fRs"
The router\(cqs ports\[char46]
.IP "\fBstatic_routes\fR: set of \fBLogical_Router_Static_Route\fRs"
One or more static routes for the router\[char46]
.IP "\fBdefault_gw\fR: optional string"
IP address to use as default gateway, if any\[char46]
.IP "\fBenabled\fR: optional boolean"
This column is used to administratively set router state\[char46]  If this column
is empty or is set to \fBtrue\fR, the router is enabled\[char46]  If this
column is set to \fBfalse\fR, the router is disabled\[char46]  A disabled
router has all ingress and egress traffic dropped\[char46]
.IP "\fBnat\fR: set of \fBNAT\fRs"
One or more NAT rules for the router\[char46] NAT rules only work on the
Gateway routers\[char46]
.ST "Options:"
Additional options for the logical router\[char46]
.IP "\fBoptions : chassis\fR: optional string"
If set, indicates that the logical router in question is a Gateway
router (which is centralized) and resides in the set chassis\[char46]  The
same value is also used by \fBovn\-controller\fR to
uniquely identify the chassis in the OVN deployment and
comes from \fBexternal_ids:system\-id\fR in the
\fBOpen_vSwitch\fR table of Open_vSwitch database\[char46]
.IP
The Gateway router can only be connected to a distributed router
via a switch if SNAT and DNAT are to be configured in the Gateway
router\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Logical_Router_Port TABLE"
A port within an L3 logical router\[char46]
.PP
Exactly one \fBLogical_Router\fR row must reference a given
logical router port\[char46]
.SS "Summary:
.TQ 3.00in
\fBname\fR
string (must be unique within table)
.TQ 3.00in
\fBnetwork\fR
string
.TQ 3.00in
\fBmac\fR
string
.TQ 3.00in
\fBenabled\fR
optional boolean
.TQ .25in
\fIAttachment:\fR
.RS .25in
.TQ 2.75in
\fBpeer\fR
optional string
.RE
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBname\fR: string (must be unique within table)"
A name for the logical router port\[char46]
.IP
In addition to provide convenience for human interaction with the
ovn-nb database, this column is used as reference by its patch port in
\fBLogical_Switch_Port\fR or another logical router port in
\fBLogical_Router_Port\fR\[char46]
.IP "\fBnetwork\fR: string"
The IP address of the router and the netmask\[char46]  For example,
\fB192\[char46]168\[char46]0\[char46]1/24\fR indicates that the router\(cqs IP address is
192\[char46]168\[char46]0\[char46]1 and that packets destined to 192\[char46]168\[char46]0\[char46]\fIx\fR should be
routed to this port\[char46]
.IP "\fBmac\fR: string"
The Ethernet address that belongs to this router port\[char46]
.IP "\fBenabled\fR: optional boolean"
This column is used to administratively set port state\[char46]  If this column
is empty or is set to \fBtrue\fR, the port is enabled\[char46]  If this
column is set to \fBfalse\fR, the port is disabled\[char46]  A disabled
port has all ingress and egress traffic dropped\[char46]
.ST "Attachment:"
A given router port serves one of two purposes:
.RS
.IP \(bu
To attach a logical switch to a logical router\[char46]  A logical router
port of this type is referenced by exactly one \fBLogical_Switch_Port\fR of type \fBrouter\fR\[char46]
The value of \fBname\fR is set as
\fBrouter\-port\fR in column \fBoptions\fR of
\fBLogical_Switch_Port\fR\[char46]  In this case \fBpeer\fR column is empty\[char46]
.IP \(bu
To connect one logical router to another\[char46]  This requires a pair of
logical router ports, each connected to a different router\[char46]  Each
router port in the pair specifies the other in its \fBpeer\fR column\[char46]  No \fBLogical_Switch\fR refers to
the router port\[char46]
.RE
.IP "\fBpeer\fR: optional string"
For a router port used to connect two logical routers, this
identifies the other router port in the pair by \fBname\fR\[char46]
.IP
For a router port attached to a logical switch, this column is empty\[char46]
.ST "Common Columns:"
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Logical_Router_Static_Route TABLE"
Each record represents a static route\[char46]
.SS "Summary:
.TQ 3.00in
\fBip_prefix\fR
string
.TQ 3.00in
\fBnexthop\fR
string
.TQ 3.00in
\fBoutput_port\fR
optional string
.SS "Details:
.IP "\fBip_prefix\fR: string"
IP prefix of this route (e\[char46]g\[char46] 192\[char46]168\[char46]100\[char46]0/24)\[char46]
.IP "\fBnexthop\fR: string"
Nexthop IP address for this route\[char46]  Nexthop IP address should be the IP
address of a connected router port or the IP address of a logical port\[char46]
.IP "\fBoutput_port\fR: optional string"
The name of the \fBLogical_Router_Port\fR via which the packet
needs to be sent out\[char46]  This is optional and when not specified,
OVN will automatically figure this out based on the
\fBnexthop\fR\[char46]
.bp
.SH "NAT TABLE"
Each record represents a NAT rule in a Gateway router\[char46]
.SS "Summary:
.TQ 3.00in
\fBtype\fR
string, one of \fBsnat\fR, \fBdnat\fR, or \fBdnat_and_snat\fR
.TQ 3.00in
\fBexternal_ip\fR
string
.TQ 3.00in
\fBlogical_ip\fR
string
.SS "Details:
.IP "\fBtype\fR: string, one of \fBsnat\fR, \fBdnat\fR, or \fBdnat_and_snat\fR"
Type of the NAT rule\[char46]
.RS
.IP \(bu
When \fBtype\fR is \fBdnat\fR, the externally
visible IP address \fBexternal_ip\fR is DNATted to the IP
address \fBlogical_ip\fR in the logical space\[char46]
.IP \(bu
When \fBtype\fR is \fBsnat\fR, IP packets
with their source IP address that either matches the IP address
in \fBlogical_ip\fR or is in the network provided by
\fBlogical_ip\fR is SNATed into the IP address in
\fBexternal_ip\fR\[char46]
.IP \(bu
When \fBtype\fR is \fBdnat_and_snat\fR, the
externally visible IP address \fBexternal_ip\fR is
DNATted to the IP address \fBlogical_ip\fR in the
logical space\[char46] In addition, IP packets with the source IP
address that matches \fBlogical_ip\fR is SNATed into
the IP address in \fBexternal_ip\fR\[char46]
.RE
.IP "\fBexternal_ip\fR: string"
An IPv4 address\[char46]
.IP "\fBlogical_ip\fR: string"
An IPv4 network (e\[char46]g 192\[char46]168\[char46]1\[char46]0/24) or an IPv4 address\[char46]
