'\" p
.\" -*- nroff -*-
.TH "vtep" 5 " DB Schema 1.3.0" "Open vSwitch 2.4.90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH NAME
vtep \- hardware_vtep database schema
.PP
This schema specifies relations that a VTEP can use to integrate
physical ports into logical switches maintained by a network
virtualization controller such as NSX\[char46]
.PP
Glossary:
.RS
.TP
VTEP
VXLAN Tunnel End Point, an entity which originates and/or terminates
VXLAN tunnels\[char46]
.TP
HSC
Hardware Switch Controller\[char46]
.TP
NVC
Network Virtualization Controller, e\[char46]g\[char46] NSX\[char46]
.TP
VRF
Virtual Routing and Forwarding instance\[char46]
.RE
.SH "TABLE SUMMARY"
.PP
The following list summarizes the purpose of each of the tables in the
\fBhardware_vtep\fR database.  Each table is described in more detail on a later
page.
.IP "Table" 1in
Purpose
.TQ 1in
\fBGlobal\fR
Top-level configuration\[char46]
.TQ 1in
\fBManager\fR
OVSDB management connection\[char46]
.TQ 1in
\fBPhysical_Switch\fR
A physical switch\[char46]
.TQ 1in
\fBTunnel\fR
A tunnel created by a physical switch\[char46]
.TQ 1in
\fBPhysical_Port\fR
A port within a physical switch\[char46]
.TQ 1in
\fBLogical_Binding_Stats\fR
Statistics for a VLAN on a physical port bound to a logical network\[char46]
.TQ 1in
\fBLogical_Switch\fR
A layer\-2 domain\[char46]
.TQ 1in
\fBUcast_Macs_Local\fR
Unicast MACs (local)
.TQ 1in
\fBUcast_Macs_Remote\fR
Unicast MACs (remote)
.TQ 1in
\fBMcast_Macs_Local\fR
Multicast MACs (local)
.TQ 1in
\fBMcast_Macs_Remote\fR
Multicast MACs (remote)
.TQ 1in
\fBLogical_Router\fR
A logical L3 router\[char46]
.TQ 1in
\fBArp_Sources_Local\fR
ARP source addresses for logical routers
.TQ 1in
\fBArp_Sources_Remote\fR
ARP source addresses for logical routers
.TQ 1in
\fBPhysical_Locator_Set\fR
Physical_Locator_Set configuration\[char46]
.TQ 1in
\fBPhysical_Locator\fR
Physical_Locator configuration\[char46]
.\" check if in troff mode (TTY)
.if t \{
.bp
.SH "TABLE RELATIONSHIPS"
.PP
The following diagram shows the relationship among tables in the
database.  Each node represents a table.  Tables that are part of the
``root set'' are shown with double borders.  Each edge leads from the
table that contains it and points to the table that its value
represents.  Edges are labeled with their column names, followed by a
constraint on the number of allowed values: \fB?\fR for zero or one,
\fB*\fR for zero or more, \fB+\fR for one or more.  Thick lines
represent strong references; thin lines represent weak references.
.RS -1in
.ps -3
.PS
linethick = 1;
linethick = 0.5;
box at 1.695952789,1.959484422 wid 1.067553656 height 0.243245 "Mcast_Macs_Remote"
box at 1.695952789,1.959484422 wid 1.01199810044444 height 0.187689444444444
linethick = 1;
box at 3.533814711,2.817604133 wid 1.0946025 height 0.243245 "Physical_Locator_Set"
linethick = 0.5;
box at 5.93225906,1.060840094 wid 0.804070672 height 0.243245 "Logical_Switch"
box at 5.93225906,1.060840094 wid 0.748515116444444 height 0.187689444444444
linethick = 0.5;
box at 3.533814711,2.0675825 wid 0.939217594 height 0.243245 "Ucast_Macs_Local"
box at 3.533814711,2.0675825 wid 0.883662038444444 height 0.187689444444444
linethick = 1;
box at 5.93225906,2.770268656 wid 0.885119906 height 0.243245 "Physical_Locator"
linethick = 1;
box at 3.533814711,2.452736633 wid 0.4189214039 height 0.243245 "Tunnel"
linethick = 0.5;
box at 0.2027057883,0.500014422 wid 0.4054067117 height 0.243245 "Global"
box at 0.2027057883,0.500014422 wid 0.349851156144444 height 0.187689444444444
linethick = 1;
box at 1.695952789,0.709448367 wid 0.858119711 height 0.243245 "Physical_Switch"
linethick = 1;
box at 1.695952789,0.3445954617 wid 0.520252406 height 0.243245 "Manager"
linethick = 1;
box at 3.533814711,0.2364876539 wid 0.729735 height 0.243245 "Physical_Port"
linethick = 0.5;
box at 3.533814711,0.601350289 wid 0.797308461 height 0.243245 "Logical_Router"
box at 3.533814711,0.601350289 wid 0.741752905444444 height 0.187689444444444
linethick = 0.5;
box at 1.695952789,1.283798461 wid 0.945931156 height 0.243245 "Mcast_Macs_Local"
box at 1.695952789,1.283798461 wid 0.890375600444444 height 0.187689444444444
linethick = 0.5;
box at 3.533814711,1.695952789 wid 1.054077883 height 0.243245 "Ucast_Macs_Remote"
box at 3.533814711,1.695952789 wid 0.998522327444444 height 0.187689444444444
linethick = 0.5;
box at 3.533814711,3.689199617 wid 1.0946025 height 0.243245 "Arp_Sources_Remote"
box at 3.533814711,3.689199617 wid 1.03904694444444 height 0.187689444444444
linethick = 0.5;
box at 3.533814711,3.324332117 wid 0.979742211 height 0.243245 "Arp_Sources_Local"
box at 3.533814711,3.324332117 wid 0.924186655444444 height 0.187689444444444
linethick = 1;
box at 5.93225906,0.1216225 wid 1.128364906 height 0.243245 "Logical_Binding_Stats"
linethick = 1;
spline -> from 1.844429537,2.082031253 to 1.844429537,2.082031253 to 1.972425056,2.183075226 to 2.165512937,2.324595167 to 2.351352117,2.418925578 to 2.617267551,2.553926553 to 2.70391142,2.53996429 to 2.986513461,2.635170383 to 3.044405771,2.654678632 to 3.105800809,2.67520851 to 3.165687728,2.695251898
"locator_set" at 2.608121539,2.655408367
linethick = 1;
spline -> from 1.805121145,1.83552677 to 1.805121145,1.83552677 to 1.925089579,1.70855288 to 2.13033971,1.517167714 to 2.351352117,1.425707594 to 2.639354197,1.306468895 to 4.653325499,1.151473181 to 5.52847236,1.088861918
"logical_switch" at 3.533814711,1.371609906
linethick = 1;
spline -> from 4.082721378,2.889507355 to 4.082721378,2.889507355 to 4.123294644,2.89315603 to 4.163624665,2.896318215 to 4.202738461,2.898653367 to 4.664368822,2.926529244 to 4.782780488,2.941172593 to 5.24338922,2.898653367 to 5.32317358,2.891307368 to 5.40782284,2.879193767 to 5.48906667,2.865280153
"locators+" at 4.722990867,2.97975125
linethick = 1;
spline -> from 4.004931627,1.9800143 to 4.004931627,1.9800143 to 4.071288863,1.968241242 to 4.138667728,1.956565482 to 4.202738461,1.94596 to 4.664028279,1.86958107 to 4.828753793,2.006917197 to 5.24338922,1.790575094 to 5.51825607,1.647011895 to 5.74398743,1.350301644 to 5.85588013,1.182803137
"logical_switch" at 4.722990867,2.00677125
linethick = 1;
spline -> from 4.005369468,2.087333994 to 4.005369468,2.087333994 to 4.4319239,2.11039362 to 5.0254417,2.156902064 to 5.24338922,2.243254039 to 5.47155303,2.333789828 to 5.68852757,2.522693895 to 5.81598795,2.648013719
"locator" at 4.722990867,2.304065289
linethick = 1;
spline -> from 3.745827053,2.515591141 to 3.745827053,2.515591141 to 3.876449618,2.552029242 to 4.047985992,2.595618746 to 4.202738461,2.621645961 to 4.636687541,2.694570812 to 5.13830738,2.732662979 to 5.48906667,2.751927983
"remote" at 4.722990867,2.790555289
linethick = 1;
spline -> from 3.744610828,2.428898623 to 3.744610828,2.428898623 to 4.070267234,2.398006508 to 4.713455663,2.360303533 to 5.24338922,2.472974617 to 5.40636337,2.507710003 to 5.57858083,2.581997026 to 5.71041962,2.647673176
"local" at 4.722990867,2.533785867
linethick = 1;
spline -> from 0.4072018598,0.528668683 to 0.4072018598,0.528668683 to 0.626842365,0.559512149 to 0.982369257,0.609377374 to 1.26438751,0.648929011
"switches*" at 0.783784039,0.675685961
linethick = 1;
spline -> from 0.4063067182,0.4224873756 to 0.4063067182,0.4224873756 to 0.4458388956,0.4101986382 to 0.487317033,0.399165045 to 0.527014617,0.3918968844 to 0.834719542,0.3355613424 to 1.195208632,0.329888869 to 1.433637381,0.3343110631
"managers*" at 0.783784039,0.4527081344
linethick = 1;
spline -> from 1.888456882,0.832189794 to 1.888456882,0.832189794 to 1.994609,0.904238963 to 2.125523459,1.000758579 to 2.229729617,1.101364711 to 2.557380632,1.41763186 to 2.644997481,1.506610881 to 2.864890961,1.905435383 to 2.943313149,2.04763641 to 2.872528854,2.134280279 to 2.986513461,2.25001625 to 3.07607627,2.34098988 to 3.210055616,2.391487542 to 3.323067243,2.419363419
"tunnels*" at 2.608121539,1.966246633
linethick = 1;
spline -> from 2.126836982,0.598577296 to 2.126836982,0.598577296 to 2.443006833,0.517187519 to 2.867761252,0.4078975405 to 3.167585039,0.3307353616
"ports*" at 2.608121539,0.587825867
linethick = 1;
spline -> from 3.898779509,0.2592602508 to 3.898779509,0.2592602508 to 4.327620444,0.2903177724 to 5.01036051,0.3544371544 to 5.24338922,0.4594606156 to 5.48809369,0.569777088 to 5.70993313,0.796530077 to 5.83252861,0.937904071
"vlan_bindings value*" at 4.722990867,0.520252406
linethick = 1;
spline -> from 3.898828158,0.1669098541 to 3.898828158,0.1669098541 to 3.997099138,0.1510746046 to 4.103640448,0.1365285536 to 4.202738461,0.1283798461 to 4.590325044,0.0965001564 to 5.02836064,0.0951428493 to 5.36695768,0.1015888418
"vlan_stats value*" at 4.722990867,0.1891910961
linethick = 1;
spline -> from 3.934050034,0.598431349 to 3.934050034,0.598431349 to 4.284614728,0.60470707 to 4.805110379,0.635696483 to 5.24338922,0.750021633 to 5.40733635,0.792735455 to 5.58101328,0.871352239 to 5.71285207,0.938779753
"switch_binding value*" at 4.722990867,0.810832883
linethick = 1;
spline -> from 1.86228372,1.407220974 to 1.86228372,1.407220974 to 1.977192658,1.499167584 to 2.127226174,1.633195579 to 2.229729617,1.777050672 to 2.307811262,1.886559571 to 2.255562236,1.959727667 to 2.351352117,2.054058078 to 2.52780204,2.227832306 to 2.69661407,2.088598868 to 2.864890961,2.270302883 to 2.981016124,2.395720005 to 2.865620696,2.514277618 to 2.986513461,2.635170383 to 3.009183895,2.657840817 to 3.03472462,2.67764096 to 3.062065358,2.695057302
"locator_set" at 2.608121539,2.331114133
linethick = 1;
spline -> from 2.171496764,1.181586912 to 2.171496764,1.181586912 to 2.414109327,1.134591978 to 2.714662849,1.084142965 to 2.986513461,1.060840094 to 3.892309192,0.983147641 to 4.96073853,1.01335867 to 5.52895885,1.039045342
"logical_switch" at 3.533814711,1.121651344
linethick = 1;
spline -> from 3.881363167,1.57379515 to 3.881363167,1.57379515 to 3.949033926,1.545821975 to 4.018358751,1.514102827 to 4.081115961,1.479756633 to 4.139592059,1.447745591 to 4.14100288,1.417048072 to 4.202738461,1.391896539 to 4.63576321,1.215495265 to 4.784921044,1.328896084 to 5.24338922,1.236511633 to 5.33630881,1.21768447 to 5.43603926,1.19433295 to 5.52944534,1.170835483
"logical_switch" at 4.722990867,1.452707789
linethick = 1;
spline -> from 4.061948255,1.620790084 to 4.061948255,1.620790084 to 4.488162144,1.570730263 to 5.04782024,1.532200255 to 5.24338922,1.64190375 to 5.63452718,1.861456687 to 5.83009616,2.40374709 to 5.90063721,2.647819123
"locator" at 4.722990867,1.702715
linethick = 1;
spline -> from 4.081699749,3.677913049 to 4.081699749,3.677913049 to 4.429686046,3.651885834 to 4.88095417,3.582415062 to 5.24338922,3.40543 to 5.49344508,3.283272361 to 5.71674399,3.040903043 to 5.83788,2.893447924
"locator" at 4.722990867,3.723010672
linethick = 1;
spline -> from 4.025412856,3.284439937 to 4.025412856,3.284439937 to 4.370966703,3.248245081 to 4.841451182,3.182325686 to 5.24338922,3.067611344 to 5.39760655,3.023583999 to 5.56252666,2.953237545 to 5.69241949,2.891988454
"locator" at 4.722990867,3.317569906
.ps +3
.PE
.RE\}
.bp
.SH "Global TABLE"
Top-level configuration for a hardware VTEP\[char46]  There must be
exactly one record in the \fBGlobal\fR table\[char46]
.SS "Summary:
.TQ 3.00in
\fBswitches\fR
set of \fBPhysical_Switch\fRs
.TQ .25in
\fIDatabase Configuration:\fR
.RS .25in
.TQ 2.75in
\fBmanagers\fR
set of \fBManager\fRs
.RE
.SS "Details:
.IP "\fBswitches\fR: set of \fBPhysical_Switch\fRs"
The physical switch or switches managed by the VTEP\[char46]
.IP
When a physical switch integrates support for this VTEP schema, which
is expected to be the most common case, this column should point to one
\fBPhysical_Switch\fR record that represents the switch
itself\[char46]  In another possible implementation, a server or a VM presents
a VTEP schema front-end interface to one or more physical switches,
presumably communicating with those physical switches over a
proprietary protocol\[char46]  In that case, this column would point to one
\fBPhysical_Switch\fR for each physical switch, and the set
might change over time as the front-end server comes to represent a
differing set of switches\[char46]
.ST "Database Configuration:"
These columns primarily configure the database server
(\fBovsdb\-server\fR), not the hardware VTEP itself\[char46]
.IP "\fBmanagers\fR: set of \fBManager\fRs"
Database clients to which the database server should connect or
to which it should listen, along with options for how these
connection should be configured\[char46]  See the \fBManager\fR
table for more information\[char46]
.bp
.SH "Manager TABLE"
Configuration for a database connection to an Open vSwitch Database
(OVSDB) client\[char46]
.PP
The database server can initiate and maintain active connections
to remote clients\[char46]  It can also listen for database connections\[char46]
.SS "Summary:
.TQ .25in
\fICore Features:\fR
.RS .25in
.TQ 2.75in
\fBtarget\fR
string (must be unique within table)
.RE
.TQ .25in
\fIClient Failure Detection and Handling:\fR
.RS .25in
.TQ 2.75in
\fBmax_backoff\fR
optional integer, at least 1,000
.TQ 2.75in
\fBinactivity_probe\fR
optional integer
.RE
.TQ .25in
\fIStatus:\fR
.RS .25in
.TQ 2.75in
\fBis_connected\fR
boolean
.TQ 2.75in
\fBstatus : last_error\fR
optional string
.TQ 2.75in
\fBstatus : state\fR
optional string, one of \fBACTIVE\fR, \fBVOID\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBBACKOFF\fR
.TQ 2.75in
\fBstatus : sec_since_connect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : sec_since_disconnect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : locks_held\fR
optional string
.TQ 2.75in
\fBstatus : locks_waiting\fR
optional string
.TQ 2.75in
\fBstatus : locks_lost\fR
optional string
.TQ 2.75in
\fBstatus : n_connections\fR
optional string, containing an integer, at least 2
.RE
.TQ .25in
\fIConnection Parameters:\fR
.RS .25in
.TQ 2.75in
\fBother_config : dscp\fR
optional string, containing an integer
.RE
.SS "Details:
.ST "Core Features:"
.IP "\fBtarget\fR: string (must be unique within table)"
Connection method for managers\[char46]
.IP
The following connection methods are currently supported:
.RS
.TP
\fBssl:\fIip\fB\fR[\fB:\fIport\fB\fR]
The specified SSL \fIport\fR (default: 6640) on the host at
the given \fIip\fR, which must be expressed as an IP address
(not a DNS name)\[char46]
.IP
SSL key and certificate configuration happens outside the
database\[char46]
.TP
\fBtcp:\fIip\fB\fR[\fB:\fIport\fB\fR]
The specified TCP \fIport\fR (default: 6640) on the host at
the given \fIip\fR, which must be expressed as an IP address
(not a DNS name)\[char46]
.TP
\fBpssl:\fR[\fIport\fR][\fB:\fIip\fB\fR]
Listens for SSL connections on the specified TCP \fIport\fR
(default: 6640)\[char46]  If \fIip\fR, which must be expressed as an
IP address (not a DNS name), is specified, then connections are
restricted to the specified local IP address\[char46]
.TP
\fBptcp:\fR[\fIport\fR][\fB:\fIip\fB\fR]
Listens for connections on the specified TCP \fIport\fR
(default: 6640)\[char46]  If \fIip\fR, which must be expressed as an
IP address (not a DNS name), is specified, then connections are
restricted to the specified local IP address\[char46]
.RE
.ST "Client Failure Detection and Handling:"
.IP "\fBmax_backoff\fR: optional integer, at least 1,000"
Maximum number of milliseconds to wait between connection attempts\[char46]
Default is implementation-specific\[char46]
.IP "\fBinactivity_probe\fR: optional integer"
Maximum number of milliseconds of idle time on connection to the
client before sending an inactivity probe message\[char46]  If the Open
vSwitch database does not communicate with the client for the
specified number of seconds, it will send a probe\[char46]  If a
response is not received for the same additional amount of time,
the database server assumes the connection has been broken
and attempts to reconnect\[char46]  Default is implementation-specific\[char46]
A value of 0 disables inactivity probes\[char46]
.ST "Status:"
.IP "\fBis_connected\fR: boolean"
\fBtrue\fR if currently connected to this manager,
\fBfalse\fR otherwise\[char46]
.IP "\fBstatus : last_error\fR: optional string"
A human-readable description of the last error on the connection
to the manager; i\[char46]e\[char46] \fBstrerror(errno)\fR\[char46]  This key
will exist only if an error has occurred\[char46]
.IP "\fBstatus : state\fR: optional string, one of \fBACTIVE\fR, \fBVOID\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBBACKOFF\fR"
The state of the connection to the manager:
.RS
.TP
\fBVOID\fR
Connection is disabled\[char46]
.TP
\fBBACKOFF\fR
Attempting to reconnect at an increasing period\[char46]
.TP
\fBCONNECTING\fR
Attempting to connect\[char46]
.TP
\fBACTIVE\fR
Connected, remote host responsive\[char46]
.TP
\fBIDLE\fR
Connection is idle\[char46]  Waiting for response to keep-alive\[char46]
.RE
.IP
These values may change in the future\[char46]  They are provided only for
human consumption\[char46]
.IP "\fBstatus : sec_since_connect\fR: optional string, containing an integer, at least 0"
The amount of time since this manager last successfully connected
to the database (in seconds)\[char46] Value is empty if manager has never
successfully connected\[char46]
.IP "\fBstatus : sec_since_disconnect\fR: optional string, containing an integer, at least 0"
The amount of time since this manager last disconnected from the
database (in seconds)\[char46] Value is empty if manager has never
disconnected\[char46]
.IP "\fBstatus : locks_held\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection
holds\[char46]  Omitted if the connection does not hold any locks\[char46]
.IP "\fBstatus : locks_waiting\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection is
currently waiting to acquire\[char46]  Omitted if the connection is not waiting
for any locks\[char46]
.IP "\fBstatus : locks_lost\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection
has had stolen by another OVSDB client\[char46]  Omitted if no locks have been
stolen from this connection\[char46]
.IP "\fBstatus : n_connections\fR: optional string, containing an integer, at least 2"
When \fBtarget\fR specifies a connection method that
listens for inbound connections (e\[char46]g\[char46] \fBptcp:\fR or
\fBpssl:\fR) and more than one connection is actually active,
the value is the number of active connections\[char46]  Otherwise, this
key-value pair is omitted\[char46]
.IP
When multiple connections are active, status columns and key-value
pairs (other than this one) report the status of one arbitrarily
chosen connection\[char46]
.ST "Connection Parameters:"
Additional configuration for a connection between the manager
and the database server\[char46]
.IP "\fBother_config : dscp\fR: optional string, containing an integer"
The Differentiated Service Code Point (DSCP) is specified using 6 bits
in the Type of Service (TOS) field in the IP header\[char46] DSCP provides a
mechanism to classify the network traffic and provide Quality of
Service (QoS) on IP networks\[char46]
The DSCP value specified here is used when establishing the
connection between the manager and the database server\[char46]  If no
value is specified, a default value of 48 is chosen\[char46]  Valid DSCP
values must be in the range 0 to 63\[char46]
.bp
.SH "Physical_Switch TABLE"
A physical switch that implements a VTEP\[char46]
.SS "Summary:
.TQ 3.00in
\fBports\fR
set of \fBPhysical_Port\fRs
.TQ 3.00in
\fBtunnels\fR
set of \fBTunnel\fRs
.TQ .25in
\fINetwork Status:\fR
.RS .25in
.TQ 2.75in
\fBmanagement_ips\fR
set of strings
.TQ 2.75in
\fBtunnel_ips\fR
set of strings
.RE
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.TQ .25in
\fIError Notification:\fR
.RS .25in
.TQ 2.75in
\fBswitch_fault_status : mac_table_exhaustion\fR
none
.TQ 2.75in
\fBswitch_fault_status : tunnel_exhaustion\fR
none
.TQ 2.75in
\fBswitch_fault_status : unspecified_fault\fR
none
.RE
.SS "Details:
.IP "\fBports\fR: set of \fBPhysical_Port\fRs"
The physical ports within the switch\[char46]
.IP "\fBtunnels\fR: set of \fBTunnel\fRs"
Tunnels created by this switch as instructed by the NVC\[char46]
.ST "Network Status:"
.IP "\fBmanagement_ips\fR: set of strings"
IPv4 or IPv6 addresses at which the switch may be contacted
for management purposes\[char46]
.IP "\fBtunnel_ips\fR: set of strings"
IPv4 or IPv6 addresses on which the switch may originate or
terminate tunnels\[char46]
.IP
This column is intended to allow a \fBManager\fR to
determine the \fBPhysical_Switch\fR that terminates
the tunnel represented by a \fBPhysical_Locator\fR\[char46]
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the switch, such as its hostname\[char46]
.IP "\fBdescription\fR: string"
An extended description for the switch, such as its switch login
banner\[char46]
.ST "Error Notification:"
An entry in this column indicates to the NVC that this switch
has encountered a fault\[char46] The switch must clear this column
when the fault has been cleared\[char46]
.IP "\fBswitch_fault_status : mac_table_exhaustion\fR: none"
Indicates that the switch has been unable to process MAC
entries requested by the NVC due to lack of table resources\[char46]
.IP "\fBswitch_fault_status : tunnel_exhaustion\fR: none"
Indicates that the switch has been unable to create tunnels
requested by the NVC due to lack of resources\[char46]
.IP "\fBswitch_fault_status : unspecified_fault\fR: none"
Indicates that an error has occurred in the switch but that no
more specific information is available\[char46]
.bp
.SH "Tunnel TABLE"
A tunnel created by a \fBPhysical_Switch\fR\[char46]
.SS "Summary:
.TQ 3.00in
\fBlocal\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBremote\fR
\fBPhysical_Locator\fR
.TQ .25in
\fIBidirectional Forwarding Detection (BFD):\fR
.RS .25in
.TQ .25in
\fIBFD Local Configuration:\fR
.RS .25in
.TQ 2.50in
\fBbfd_config_local : bfd_dst_mac\fR
optional string
.TQ 2.50in
\fBbfd_config_local : bfd_dst_ip\fR
optional string
.RE
.TQ .25in
\fIBFD Remote Configuration:\fR
.RS .25in
.TQ 2.50in
\fBbfd_config_remote : bfd_dst_mac\fR
optional string
.TQ 2.50in
\fBbfd_config_remote : bfd_dst_ip\fR
optional string
.RE
.TQ .25in
\fIBFD Parameters:\fR
.RS .25in
.TQ 2.50in
\fBbfd_params : enable\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : min_rx\fR
optional string, containing an integer, at least 1
.TQ 2.50in
\fBbfd_params : min_tx\fR
optional string, containing an integer, at least 1
.TQ 2.50in
\fBbfd_params : decay_min_rx\fR
optional string, containing an integer
.TQ 2.50in
\fBbfd_params : forwarding_if_rx\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : cpath_down\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_params : check_tnl_key\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.RE
.TQ .25in
\fIBFD Status:\fR
.RS .25in
.TQ 2.50in
\fBbfd_status : enabled\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_status : state\fR
optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR
.TQ 2.50in
\fBbfd_status : forwarding\fR
optional string, either \fBtrue\fR or \fBfalse\fR
.TQ 2.50in
\fBbfd_status : diagnostic\fR
optional string
.TQ 2.50in
\fBbfd_status : remote_state\fR
optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR
.TQ 2.50in
\fBbfd_status : remote_diagnostic\fR
optional string
.TQ 2.50in
\fBbfd_status : info\fR
optional string
.RE
.RE
.SS "Details:
.IP "\fBlocal\fR: \fBPhysical_Locator\fR"
Tunnel end-point local to the physical switch\[char46]
.IP "\fBremote\fR: \fBPhysical_Locator\fR"
Tunnel end-point remote to the physical switch\[char46]
.ST "Bidirectional Forwarding Detection (BFD):"
BFD, defined in RFC 5880, allows point to point detection of
connectivity failures by occasional transmission of BFD control
messages\[char46] VTEPs are expected to implement BFD\[char46]
.PP
BFD operates by regularly transmitting BFD control messages at a
rate negotiated independently in each direction\[char46]  Each endpoint
specifies the rate at which it expects to receive control messages,
and the rate at which it\(cqs willing to transmit them\[char46]  An endpoint
which fails to receive BFD control messages for a period of three
times the expected reception rate will signal a connectivity
fault\[char46]  In the case of a unidirectional connectivity issue, the
system not receiving BFD control messages will signal the problem
to its peer in the messages it transmits\[char46]
.PP
A hardware VTEP is expected to use BFD to determine reachability of
devices at the end of the tunnels with which it exchanges data\[char46] This
can enable the VTEP to choose a functioning service node among a set of
service nodes providing high availability\[char46] It also enables the NVC to
report the health status of tunnels\[char46]
.PP
In most cases the BFD peer of a hardware VTEP will be an Open vSwitch
instance\[char46] The Open vSwitch implementation of BFD aims to comply
faithfully with the requirements put forth in RFC 5880\[char46]  Open vSwitch
does not implement the optional Authentication or ``Echo Mode\(cq\(cq
features\[char46]
.ST "BFD Local Configuration:"
The HSC writes the key-value pairs in the
\fBbfd_config_local\fR column to specifiy the local
configurations to be used for BFD sessions on this tunnel\[char46]
.IP "\fBbfd_config_local : bfd_dst_mac\fR: optional string"
Set to an Ethernet address in the form
\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR
to set the MAC expected as destination for received BFD packets\[char46]
The default is \fB00:23:20:00:00:01\fR\[char46]
.IP "\fBbfd_config_local : bfd_dst_ip\fR: optional string"
Set to an IPv4 address to set the IP address that is expected as destination
for received BFD packets\[char46]  The default is \fB169\[char46]254\[char46]1\[char46]0\fR\[char46]
.ST "BFD Remote Configuration:"
The \fBbfd_config_remote\fR column is the remote
counterpart of the \fBbfd_config_local\fR column\[char46]
The NVC writes the key-value pairs in this column\[char46]
.IP "\fBbfd_config_remote : bfd_dst_mac\fR: optional string"
Set to an Ethernet address in the form
\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR:\fIxx\fR
to set the destination MAC to be used for transmitted BFD packets\[char46]
The default is \fB00:23:20:00:00:01\fR\[char46]
.IP "\fBbfd_config_remote : bfd_dst_ip\fR: optional string"
Set to an IPv4 address to set the IP address used as destination
for transmitted BFD packets\[char46]  The default is \fB169\[char46]254\[char46]1\[char46]1\fR\[char46]
.ST "BFD Parameters:"
The NVC sets up key-value pairs in the \fBbfd_params\fR
column to enable and configure BFD\[char46]
.IP "\fBbfd_params : enable\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
True to enable BFD on this tunnel\[char46]
The default is False\[char46]
.IP "\fBbfd_params : min_rx\fR: optional string, containing an integer, at least 1"
The shortest interval, in milliseconds, at which this BFD session
offers to receive BFD control messages\[char46]  The remote endpoint may
choose to send messages at a slower rate\[char46]  Defaults to
\fB1000\fR\[char46]
.IP "\fBbfd_params : min_tx\fR: optional string, containing an integer, at least 1"
The shortest interval, in milliseconds, at which this BFD session is
willing to transmit BFD control messages\[char46]  Messages will actually be
transmitted at a slower rate if the remote endpoint is not willing to
receive as quickly as specified\[char46]  Defaults to \fB100\fR\[char46]
.IP "\fBbfd_params : decay_min_rx\fR: optional string, containing an integer"
An alternate receive interval, in milliseconds, that must be greater
than or equal to \fBbfd:min_rx\fR\[char46]  The
implementation switches from \fBbfd:min_rx\fR to \fBbfd:decay_min_rx\fR when there is no obvious incoming
data traffic at the interface, to reduce the CPU and bandwidth cost
of monitoring an idle interface\[char46]  This feature may be disabled by
setting a value of 0\[char46]  This feature is reset whenever \fBbfd:decay_min_rx\fR or \fBbfd:min_rx\fR
changes\[char46]
.IP "\fBbfd_params : forwarding_if_rx\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
True to consider the interface capable of packet I/O as long as it
continues to receive any packets (not just BFD packets)\[char46]  This
prevents link congestion that causes consecutive BFD control packets
to be lost from marking the interface down\[char46]
.IP "\fBbfd_params : cpath_down\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Set to true to notify the remote endpoint that traffic should not be
forwarded to this system for some reason other than a connectivty
failure on the interface being monitored\[char46]  The typical underlying
reason is ``concatenated path down,\(cq\(cq that is, that connectivity
beyond the local system is down\[char46]  Defaults to false\[char46]
.IP "\fBbfd_params : check_tnl_key\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Set to true to make BFD accept only control messages with a tunnel
key of zero\[char46]  By default, BFD accepts control messages with any
tunnel key\[char46]
.ST "BFD Status:"
The VTEP sets key-value pairs in the \fBbfd_status\fR
column to report the status of BFD on this tunnel\[char46]  When BFD is
not enabled, with \fBbfd_params:enable\fR, the
HSC clears all key-value pairs from \fBbfd_status\fR\[char46]
.IP "\fBbfd_status : enabled\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Set to true if the BFD session has been successfully
enabled\[char46] Set to false if the VTEP cannot support BFD or has
insufficient resources to enable BFD on this tunnel\[char46] The NVC
will disable the BFD monitoring on the other side of the tunnel
once this value is set to false\[char46]
.IP "\fBbfd_status : state\fR: optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR"
Reports the state of the BFD session\[char46]  The BFD session is fully
healthy and negotiated if \fBUP\fR\[char46]
.IP "\fBbfd_status : forwarding\fR: optional string, either \fBtrue\fR or \fBfalse\fR"
Reports whether the BFD session believes this tunnel
may be used to forward traffic\[char46]  Typically this means the local session
is signaling \fBUP\fR, and the remote system isn\(cqt signaling a
problem such as concatenated path down\[char46]
.IP "\fBbfd_status : diagnostic\fR: optional string"
In case of a problem, set to an error message that reports what the
local BFD session thinks is wrong\[char46]  The error messages are defined
in section 4\[char46]1 of [RFC 5880]\[char46]
.IP "\fBbfd_status : remote_state\fR: optional string, one of \fBdown\fR, \fBinit\fR, \fBup\fR, or \fBadmin_down\fR"
Reports the state of the remote endpoint\(cqs BFD session\[char46]
.IP "\fBbfd_status : remote_diagnostic\fR: optional string"
In case of a problem, set to an error message that reports what the
remote endpoint\(cqs BFD session thinks is wrong\[char46]  The error messages
are defined in section 4\[char46]1 of [RFC 5880]\[char46]
.IP "\fBbfd_status : info\fR: optional string"
A short message providing further information about the BFD status
(possibly including reasons why BFD could not be enabled)\[char46]
.bp
.SH "Physical_Port TABLE"
A port within a \fBPhysical_Switch\fR\[char46]
.SS "Summary:
.TQ 3.00in
\fBvlan_bindings\fR
map of integer-\fBLogical_Switch\fR pairs, key in range 0 to 4,095
.TQ 3.00in
\fBvlan_stats\fR
map of integer-\fBLogical_Binding_Stats\fR pairs, key in range 0 to 4,095
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string
.TQ 2.75in
\fBdescription\fR
string
.RE
.TQ .25in
\fIError Notification:\fR
.RS .25in
.TQ 2.75in
\fBport_fault_status : invalid_vlan_map\fR
none
.TQ 2.75in
\fBport_fault_status : unspecified_fault\fR
none
.RE
.SS "Details:
.IP "\fBvlan_bindings\fR: map of integer-\fBLogical_Switch\fR pairs, key in range 0 to 4,095"
Identifies how VLANs on the physical port are bound to logical switches\[char46]
If, for example, the map contains a (VLAN, logical switch) pair, a packet
that arrives on the port in the VLAN is considered to belong to the
paired logical switch\[char46]
.IP "\fBvlan_stats\fR: map of integer-\fBLogical_Binding_Stats\fR pairs, key in range 0 to 4,095"
Statistics for VLANs bound to logical switches on the physical port\[char46]  An
implementation that fully supports such statistics would populate this
column with a mapping for every VLAN that is bound in \fBvlan_bindings\fR\[char46]  An implementation that does not support such
statistics or only partially supports them would not populate this column
or partially populate it, respectively\[char46]
.ST "Identification:"
.IP "\fBname\fR: string"
Symbolic name for the port\[char46]  The name ought to be unique within a given
\fBPhysical_Switch\fR, but the database is not capable of
enforcing this\[char46]
.IP "\fBdescription\fR: string"
An extended description for the port\[char46]
.ST "Error Notification:"
An entry in this column indicates to the NVC that the physical port has
encountered a fault\[char46] The switch must clear this column when the errror
has been cleared\[char46]
.IP "\fBport_fault_status : invalid_vlan_map\fR: none"
Indicates that a VLAN-to-logical-switch mapping requested by
the controller could not be instantiated by the switch
because of a conflict with local configuration\[char46]
.IP "\fBport_fault_status : unspecified_fault\fR: none"
Indicates that an error has occurred on the port but that no
more specific information is available\[char46]
.bp
.SH "Logical_Binding_Stats TABLE"
Reports statistics for the \fBLogical_Switch\fR with which a VLAN
on a \fBPhysical_Port\fR is associated\[char46]
.SS "Summary:
.TQ .25in
\fIStatistics:\fR
.RS .25in
.TQ 2.75in
\fBpackets_from_local\fR
integer
.TQ 2.75in
\fBbytes_from_local\fR
integer
.TQ 2.75in
\fBpackets_to_local\fR
integer
.TQ 2.75in
\fBbytes_to_local\fR
integer
.RE
.SS "Details:
.ST "Statistics:"
These statistics count only packets to which the binding applies\[char46]
.IP "\fBpackets_from_local\fR: integer"
Number of packets sent by the \fBPhysical_Switch\fR\[char46]
.IP "\fBbytes_from_local\fR: integer"
Number of bytes in packets sent by the \fBPhysical_Switch\fR\[char46]
.IP "\fBpackets_to_local\fR: integer"
Number of packets received by the \fBPhysical_Switch\fR\[char46]
.IP "\fBbytes_to_local\fR: integer"
Number of bytes in packets received by the \fBPhysical_Switch\fR\[char46]
.bp
.SH "Logical_Switch TABLE"
A logical Ethernet switch, whose implementation may span physical and
virtual media, possibly crossing L3 domains via tunnels; a logical layer\-2
domain; an Ethernet broadcast domain\[char46]
.SS "Summary:
.TQ .25in
\fIPer Logical-Switch Tunnel Key:\fR
.RS .25in
.TQ 2.75in
\fBtunnel_key\fR
optional integer
.RE
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.SS "Details:
.ST "Per Logical-Switch Tunnel Key:"
Tunnel protocols tend to have a field that allows the tunnel
to be partitioned into sub-tunnels: VXLAN has a VNI, GRE and
STT have a key, CAPWAP has a WSI, and so on\[char46]  We call these
generically ``tunnel keys\[char46]\(cq\(cq  Given that one needs to use a
tunnel key at all, there are at least two reasonable ways to
assign their values:
.RS
.IP \(bu
Per \fBLogical_Switch\fR+\fBPhysical_Locator\fR
pair\[char46]  That is, each logical switch may be assigned a different
tunnel key on every \fBPhysical_Locator\fR\[char46]  This model is
especially flexible\[char46]
.IP
In this model, \fBPhysical_Locator\fR carries the tunnel
key\[char46]  Therefore, one \fBPhysical_Locator\fR record will
exist for each logical switch carried at a given IP destination\[char46]
.IP \(bu
Per \fBLogical_Switch\fR\[char46]  That is, every tunnel
associated with a particular logical switch carries the same tunnel
key, regardless of the \fBPhysical_Locator\fR to which the
tunnel is addressed\[char46]  This model may ease switch implementation
because it imposes fewer requirements on the hardware datapath\[char46]
.IP
In this model, \fBLogical_Switch\fR carries the tunnel
key\[char46]  Therefore, one \fBPhysical_Locator\fR record will
exist for each IP destination\[char46]
.RE
.IP "\fBtunnel_key\fR: optional integer"
This column is used only in the tunnel key per \fBLogical_Switch\fR model (see above), because only in that
model is there a tunnel key associated with a logical switch\[char46]
.IP
For \fBvxlan_over_ipv4\fR encapsulation, this column
is the VXLAN VNI that identifies a logical switch\[char46]  It must
be in the range 0 to 16,777,215\[char46]
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the logical switch\[char46]
.IP "\fBdescription\fR: string"
An extended description for the logical switch, such as its switch
login banner\[char46]
.bp
.SH "Ucast_Macs_Local TABLE"
Mapping of unicast MAC addresses to tunnels (physical
locators)\[char46] This table is written by the HSC, so it contains the
MAC addresses that have been learned on physical ports by a
VTEP\[char46]
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the VTEP\[char46]
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies\[char46]
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The physical locator to be used to reach this MAC address\[char46] In
this table, the physical locator will be one of the tunnel IP
addresses of the appropriate VTEP\[char46]
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds\[char46] Optional field for
the purpose of ARP supression\[char46]
.bp
.SH "Ucast_Macs_Remote TABLE"
Mapping of unicast MAC addresses to tunnels (physical
locators)\[char46] This table is written by the NVC, so it contains the
MAC addresses that the NVC has learned\[char46] These include VM MAC
addresses, in which case the physical locators will be
hypervisor IP addresses\[char46] The NVC will also report MACs that it
has learned from other HSCs in the network, in which case the
physical locators will be tunnel IP addresses of the
corresponding VTEPs\[char46]
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the NVC\[char46]
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies\[char46]
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The physical locator to be used to reach this MAC address\[char46] In
this table, the physical locator will be either a hypervisor IP
address or a tunnel IP addresses of another VTEP\[char46]
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds\[char46] Optional field for
the purpose of ARP supression\[char46]
.bp
.SH "Mcast_Macs_Local TABLE"
Mapping of multicast MAC addresses to tunnels (physical
locators)\[char46] This table is written by the HSC, so it contains the
MAC addresses that have been learned on physical ports by a
VTEP\[char46] These may be learned by IGMP snooping, for example\[char46] This
table also specifies how to handle unknown unicast and broadcast packets\[char46]
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator_set\fR
\fBPhysical_Locator_Set\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the VTEP\[char46]
.IP
The keyword \fBunknown\-dst\fR is used as a special
``Ethernet address\(cq\(cq that indicates the locations to which
packets in a logical switch whose destination addresses do not
otherwise appear in \fBUcast_Macs_Local\fR (for
unicast addresses) or \fBMcast_Macs_Local\fR (for
multicast addresses) should be sent\[char46]
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies\[char46]
.IP "\fBlocator_set\fR: \fBPhysical_Locator_Set\fR"
The physical locator set to be used to reach this MAC address\[char46] In
this table, the physical locator set will be contain one or more tunnel IP
addresses of the appropriate VTEP(s)\[char46]
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds\[char46] Optional field for
the purpose of ARP supression\[char46]
.bp
.SH "Mcast_Macs_Remote TABLE"
Mapping of multicast MAC addresses to tunnels (physical
locators)\[char46] This table is written by the NVC, so it contains the
MAC addresses that the NVC has learned\[char46] This
table also specifies how to handle unknown unicast and broadcast
packets\[char46]
.PP
Multicast packet replication may be handled by a service node,
in which case the physical locators will be IP addresses of
service nodes\[char46] If the VTEP supports replication onto multiple
tunnels, then this may be used to replicate directly onto
VTEP-hyperisor tunnels\[char46]
.SS "Summary:
.TQ 3.00in
\fBMAC\fR
string
.TQ 3.00in
\fBlogical_switch\fR
\fBLogical_Switch\fR
.TQ 3.00in
\fBlocator_set\fR
\fBPhysical_Locator_Set\fR
.TQ 3.00in
\fBipaddr\fR
string
.SS "Details:
.IP "\fBMAC\fR: string"
A MAC address that has been learned by the NVC\[char46]
.IP
The keyword \fBunknown\-dst\fR is used as a special
``Ethernet address\(cq\(cq that indicates the locations to which
packets in a logical switch whose destination addresses do not
otherwise appear in \fBUcast_Macs_Remote\fR (for
unicast addresses) or \fBMcast_Macs_Remote\fR (for
multicast addresses) should be sent\[char46]
.IP "\fBlogical_switch\fR: \fBLogical_Switch\fR"
The Logical switch to which this mapping applies\[char46]
.IP "\fBlocator_set\fR: \fBPhysical_Locator_Set\fR"
The physical locator set to be used to reach this MAC address\[char46] In
this table, the physical locator set will be either a service node IP
address or a set of tunnel IP addresses of hypervisors (and
potentially other VTEPs)\[char46]
.IP "\fBipaddr\fR: string"
The IP address to which this MAC corresponds\[char46] Optional field for
the purpose of ARP supression\[char46]
.bp
.SH "Logical_Router TABLE"
A logical router, or VRF\[char46] A logical router may be connected to one or more
logical switches\[char46] Subnet addresses and interface addresses may be configured on the
interfaces\[char46]
.SS "Summary:
.TQ 3.00in
\fBswitch_binding\fR
map of string-\fBLogical_Switch\fR pairs
.TQ 3.00in
\fBstatic_routes\fR
map of string-string pairs
.TQ .25in
\fIIdentification:\fR
.RS .25in
.TQ 2.75in
\fBname\fR
string (must be unique within table)
.TQ 2.75in
\fBdescription\fR
string
.RE
.SS "Details:
.IP "\fBswitch_binding\fR: map of string-\fBLogical_Switch\fR pairs"
Maps from an IPv4 or IPv6 address prefix in CIDR notation to a
logical switch\[char46] Multiple prefixes may map to the same switch\[char46] By
writing a 32-bit (or 128-bit for v6) address with a /N prefix
length, both the router\(cqs interface address and the subnet
prefix can be configured\[char46] For example, 192\[char46]68\[char46]1\[char46]1/24 creates a
/24 subnet for the logical switch attached to the interface and
assigns the address 192\[char46]68\[char46]1\[char46]1 to the router interface\[char46]
.IP "\fBstatic_routes\fR: map of string-string pairs"
One or more static routes, mapping IP prefixes to next hop IP addresses\[char46]
.ST "Identification:"
.IP "\fBname\fR: string (must be unique within table)"
Symbolic name for the logical router\[char46]
.IP "\fBdescription\fR: string"
An extended description for the logical router\[char46]
.bp
.SH "Arp_Sources_Local TABLE"
MAC address to be used when a VTEP issues ARP requests on behalf
of a logical router\[char46]
.PP
A distributed logical router is implemented by a set of VTEPs
(both hardware VTEPs and vswitches)\[char46] In order for a given VTEP
to populate the local ARP cache for a logical router, it issues
ARP requests with a source MAC address that is unique to the VTEP\[char46] A
single per-VTEP MAC can be re-used across all logical
networks\[char46] This table contains the MACs that are used by the
VTEPs of a given HSC\[char46] The table provides the mapping from MAC to
physical locator for each VTEP so that replies to the ARP
requests can be sent back to the correct VTEP using the
appropriate physical locator\[char46]
.SS "Summary:
.TQ 3.00in
\fBsrc_mac\fR
string
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.SS "Details:
.IP "\fBsrc_mac\fR: string"
The source MAC to be used by a given VTEP\[char46]
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The \fBPhysical_Locator\fR to use for replies to ARP
requests from this MAC address\[char46]
.bp
.SH "Arp_Sources_Remote TABLE"
MAC address to be used when a remote VTEP issues ARP requests on behalf
of a logical router\[char46]
.PP
This table is the remote counterpart of \fBArp_sources_local\fR\[char46] The NVC writes this table to notify
the HSC of the MACs that will be used by remote VTEPs when they
issue ARP requests on behalf of a distributed logical router\[char46]
.SS "Summary:
.TQ 3.00in
\fBsrc_mac\fR
string
.TQ 3.00in
\fBlocator\fR
\fBPhysical_Locator\fR
.SS "Details:
.IP "\fBsrc_mac\fR: string"
The source MAC to be used by a given VTEP\[char46]
.IP "\fBlocator\fR: \fBPhysical_Locator\fR"
The \fBPhysical_Locator\fR to use for replies to ARP
requests from this MAC address\[char46]
.bp
.SH "Physical_Locator_Set TABLE"
A set of one or more \fBPhysical_Locator\fRs\[char46]
.PP
This table exists only because OVSDB does not have a way to
express the type ``map from string to one or more \fBPhysical_Locator\fR records\[char46]\(cq\(cq
.SS "Summary:
.TQ 3.00in
\fBlocators\fR
immutable set of 1 or more \fBPhysical_Locator\fRs
.SS "Details:
.IP "\fBlocators\fR: immutable set of 1 or more \fBPhysical_Locator\fRs"
.bp
.SH "Physical_Locator TABLE"
Identifies an endpoint to which logical switch traffic may be
encapsulated and forwarded\[char46]
.PP
For the \fBvxlan_over_ipv4\fR encapsulation, the only
encapsulation defined so far, all endpoints associated with a given \fBLogical_Switch\fR must use a common tunnel key, which is carried
in the \fBtunnel_key\fR column of \fBLogical_Switch\fR\[char46]
.PP
For some encapsulations yet to be defined, we expect \fBPhysical_Locator\fR to identify both an endpoint and a tunnel key\[char46]
When the first such encapsulation is defined, we expect to add a
``tunnel_key\(cq\(cq column to \fBPhysical_Locator\fR to allow the
tunnel key to be defined\[char46]
.PP
See the ``Per Logical-Switch Tunnel Key\(cq\(cq section in the \fBLogical_Switch\fR table for further discussion of the model\[char46]
.SS "Summary:
.TQ 3.00in
\fBencapsulation_type\fR
immutable string, must be \fBvxlan_over_ipv4\fR
.TQ 3.00in
\fBdst_ip\fR
immutable string
.SS "Details:
.IP "\fBencapsulation_type\fR: immutable string, must be \fBvxlan_over_ipv4\fR"
The type of tunneling encapsulation\[char46]
.IP "\fBdst_ip\fR: immutable string"
For \fBvxlan_over_ipv4\fR encapsulation, the IPv4 address of the
VXLAN tunnel endpoint\[char46]
.IP
We expect that this column could be used for IPv4 or IPv6 addresses in
encapsulations to be introduced later\[char46]
